org.gradle.jvmargs=-Xmx8G

artifactVersion=1.0.4
groupId=at.asitplus.warden

jdk.version=17
android.minSdk=30
android.compileSdk=34
android.useAndroidX=true
android.raiseTestToJdkTarget=true
kotlin.native.cacheKind.iosSimulatorArm64=none

sbombastic.enabled=true
sbombastic.supplier.name=A-SIT Plus GmbH
sbombastic.supplier.urls=https://plus.a-sit.at, https://github.com/a-sit-plus
sbombastic.supplier.contactName=A-SIT Plus Opensource
sbombastic.supplier.email=opensource@a-sit.at
sbombastic.license.id=Apache-2.0
sbombastic.license.name=Apache License 2.0
sbombastic.license.url=https://www.apache.org/licenses/LICENSE-2.0.txt
sbombastic.supplier.mappingsUrl=file:suppliers.json
