[versions]

## do not track latest and greatest for better downstream compat
kotlin = "2.4.0"

guava = "33.5.0-jre"
autovalue = "1.11.0"
signum = "3.21.0"
supreme = "0.13.0"
agp = "8.13.2"
cbor = "0.9"
gson = "2.13.2"
errorprone = "2.43.0"
protobuf = "4.33.0"
devicecheck = "0.9.6"
jackson = "2.20.0"
schemakenerator = "2.5.0"
yamlkt = "0.13.0"
androidx = "1.9.1"
coroutines = "1.10.2"
hoplite = "2.9.0"
spring-boot = "4.0.0"

#keep it nice and lenient
semver = "1.2.0"
serialization ="1.10.0"

slf4j = "1.7.36"
testballoon = "1.0.0-K2.4.0"
#testballoonAddons = "0.14.0"
asp = "20260610"
sbombastic ="0.0.3"
pitest = "1.19.0-rc.3"
pitest-junit5 = "1.2.2"


[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
autovalue-value = { group = "com.google.auto.value", name = "auto-value", version.ref = "autovalue" }
autovalue-annotations = { group = "com.google.auto.value", name = "auto-value-annotations", version.ref = "autovalue" }
androidx-annotations = { group = "androidx.annotation", name = "annotation", version.ref = "androidx" }
cbor = { group = "co.nstant.in", name = "cbor", version.ref = "cbor" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
errorprone-annotations = { group = "com.google.errorprone", name = "error_prone_annotations", version.ref = "errorprone" }
protobuf-kotlinlite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines"}
hoplite-core = { group = "com.sksamuel.hoplite", name = "hoplite-core", version.ref = "hoplite" }
hoplite-yaml = { group = "com.sksamuel.hoplite", name = "hoplite-yaml", version.ref = "hoplite" }
hoplite-json = { group = "com.sksamuel.hoplite", name = "hoplite-json", version.ref = "hoplite" }
spring-boot = { group = "org.springframework.boot", name = "spring-boot", version.ref = "spring-boot" }
spring-boot-autoconfigure = { group = "org.springframework.boot", name = "spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }

yamltk = {module = "net.mamoe.yamlkt:yamlkt", version.ref = "yamlkt"}
signum = { group = "at.asitplus.signum", name = "indispensable", version.ref = "signum" }
supreme = { group = "at.asitplus.signum", name = "supreme", version.ref = "supreme" }
devicecheck = { group = "ch.veehait.devicecheck", name = "devicecheck-appattest", version.ref = "devicecheck" }
jackson-cbor = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-cbor", version.ref = "jackson" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
semver = { group = "net.swiftzer.semver", name = "semver", version.ref = "semver" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-reload4j = { group = "org.slf4j", name = "slf4j-reload4j", version.ref = "slf4j" }
schemakenerator-core = { group = "io.github.smiley4", name = "schema-kenerator-core", version.ref = "schemakenerator" }
schemakenerator-serialization = { group = "io.github.smiley4", name = "schema-kenerator-serialization", version.ref = "schemakenerator" }
schemakenerator-jsonschema = { group = "io.github.smiley4", name = "schema-kenerator-jsonschema", version.ref = "schemakenerator" }

[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }
agp = { id = "com.android.kotlin.multiplatform.library", version.ref= "agp"}
sbombastic = { id = "at.asitplus.gradle.sbombastic", version.ref= "sbombastic"}
pitest = { id = "info.solidsoft.pitest", version.ref = "pitest" }
