[versions]
signum = "3.16.2"
supreme = "0.8.2"
warden = "2.3.3"
runner = "1.5.2"
kotestExtensionsAndroid = "0.1.3"
kotestRunnerAndroid = "1.1.1"
core = "1.5.0"

[libraries]
signum = { group = "at.asitplus.signum", name = "indispensable", version.ref = "signum" }
supreme = { group = "at.asitplus.signum", name = "supreme", version.ref = "supreme" }
warden = { group = "at.asitplus", name = "warden", version.ref = "warden" }
core = { module = "androidx.test:core", version.ref = "core" }
kotest-extensions-android = { module = "br.com.colman:kotest-extensions-android", version.ref = "kotestExtensionsAndroid" }
kotest-runner-android = { module = "br.com.colman:kotest-runner-android", version.ref = "kotestRunnerAndroid" }
rules = { module = "androidx.test:rules", version.ref = "core" }
runner = { module = "androidx.test:runner", version.ref = "runner" }