@file:OptIn(ExperimentalTime::class)

package at.asitplus.attestation.android

import at.asitplus.KmmResult
import at.asitplus.catchingUnwrapped
import at.asitplus.signum.indispensable.asn1.*
import at.asitplus.signum.indispensable.asn1.encoding.*
import at.asitplus.signum.indispensable.misc.BitLength
import kotlinx.datetime.Month
import kotlinx.datetime.number
import kotlin.time.Duration
import kotlin.time.Duration.Companion.seconds
import kotlin.time.ExperimentalTime
import kotlin.time.Instant

/**
 * #### Intro
 * Authorization List ASN.1 sequence as [defined by Google](https://source.android.com/docs/security/features/keystore/attestation#schema).
 * Enum values as in the [keymint definitions](https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/android/hardware/security/keymint/)
 * This is the meat of the [AttestationKeyDescription] attestation certificate extension.
 * It is also used for secure key import.
 *
 * Every value is nullable because two authorization lists are present in an attestation extension:
 * once for software-enforced values, and once for hardware-enforced value.
 * The actual values are scattered across both instances.
 *
 * #### On Parsing
 * **Parsing is lenient:** If a value fails to parse, it is set to null. In reality,
 * you won't care whether a value is structurally illegal or absent:
 * * If you want to enforce it, it must be present and structurally valid, fulfilling your constraints
 * * If you don't care for it, you don't care whether it is present, invalid, or absent altogether
 * In case you still want to explore the raw value, check the raw ASN.1 Sequence from the certificate extension and fetch
 * the raw value according to the explicit tag denoting said value.
 *
 * #### Structural Properties and Design Decisions
 * **Structurally, this data structure follows the ASN.1 schema _exactly_**, meaning that it is a structural 1:1 mapping
 * if the underlying ASN.1 structure.
 * This as both advantages and disadvantages. The main disadvantage is that it is a bit cumbersome to use. The benefits
 * far outweigh the shortcomings of this approach, though:
 * * Just check the schema, and you know what's what. That means that there are no booleans, but an object indicating
 * `true` or `false` is either present or absent
 * * Re-Encoding produces the exact same ASN.1 structure that was parsed, byte-for-byte!
 * * Creating Attestation statements for testing, fun, profit, or malicious intentions is a peak no-brainer;
 * just follow the schema and set values!
 *
 * #### Closing Remarks
 * Note that values found in header files as the one below conform with (autogenerated from?) the aidl files
 * https://android.googlesource.com/platform/hardware/libhardware/+/refs/heads/main/include_all/hardware/keymaster_defs.h
 *
 * Also note that some online sources do not match the specified ASN.1 values (in the following one PKCS7 has value 65 instead of 64)
 * https://android.googlesource.com/platform/frameworks/base/+blame/45ff13e/core/java/android/security/keymaster/KeymasterDefs.java
 */
data class AuthorizationList private constructor(
    // @formatter:off
    val purposeIndexed                     : IndexedValue<Set<AttestationValue<KeyPurpose>>>?             = null,
    val algorithmIndexed                   : IndexedValue<AttestationValue<Algorithm>>?                   = null,
    val keySizeIndexed                     : IndexedValue<AttestationValue<KeySize>>?                     = null,
    val digestIndexed                      : IndexedValue<Set<AttestationValue<Digest>>>?                 = null,
    val paddingIndexed                     : IndexedValue<Set<AttestationValue<Padding>>>?                = null,
    val ecCurveIndexed                     : IndexedValue<AttestationValue<ECCurve>>?                     = null,
    val rsaPublicExponentIndexed           : IndexedValue<AttestationValue<RsaPublicExponent>>?           = null,
    val mgfDigestIndexed                   : IndexedValue<Set<AttestationValue<MgfDigest>>>?              = null,
    val rollbackResistanceIndexed          : IndexedValue<AttestationValue<RollbackResistance>>?          = null,
    val earlyBootOnlyIndexed               : IndexedValue<AttestationValue<EarlyBootOnly>>?               = null,
    val activeDateTimeIndexed              : IndexedValue<AttestationValue<ActiveDateTime>>?              = null,
    val originationExpireDateTimeIndexed   : IndexedValue<AttestationValue<OriginationExpireDateTime>>?   = null,
    val usageExpireDateTimeIndexed         : IndexedValue<AttestationValue<UsageExpireDateTime>>?         = null,
    val usageCountLimitIndexed             : IndexedValue<AttestationValue<UsageCountLimit>>?             = null,
    val noAuthRequiredIndexed              : IndexedValue<AttestationValue<NoAuthRequired>>?              = null,
    val userAuthTypeIndexed                : IndexedValue<AttestationValue<UserAuth>>?                    = null,
    val authTimeoutIndexed                 : IndexedValue<AttestationValue<AuthTimeout>>?                 = null,
    val allowWhileOnBodyIndexed            : IndexedValue<AttestationValue<AllowWhileOnBody>>?            = null,
    val trustedUserPresenceRequiredIndexed : IndexedValue<AttestationValue<TrustedUserPresenceRequired>>? = null,
    val trustedConfirmationRequiredIndexed : IndexedValue<AttestationValue<TrustedConfirmationRequired>>? = null,
    val unlockedDeviceRequiredIndexed      : IndexedValue<AttestationValue<UnlockedDeviceRequired>>?      = null,
    val allApplicationsIndexed             : IndexedValue<AttestationValue<AllApplications>>?             = null, // only up to version v4 // TODO add opt-in annotation?
    val creationDateTimeIndexed            : IndexedValue<AttestationValue<CreationDateTime>>?            = null,
    val originIndexed                      : IndexedValue<AttestationValue<Origin>>?                      = null,
    val rollbackResistantIndexed           : IndexedValue<AttestationValue<RollbackResistent>>?           = null, // only up to version v2, "resistance" afterwards // TODO add opt-in annotation?
    val rootOfTrustIndexed                 : IndexedValue<AttestationValue<RootOfTrust>>?                 = null,
    val osVersionIndexed                   : IndexedValue<AttestationValue<OsVersion>>?                   = null,
    val osPatchLevelIndexed                : IndexedValue<AttestationValue<OsPatchLevel>>?                = null,
    val attestationApplicationIdIndexed    : IndexedValue<AttestationValue<AttestationApplicationId>>?    = null,
    val attestationIdBrandIndexed          : IndexedValue<AttestationValue<AttestationId.Brand>>?         = null,
    val attestationIdDeviceIndexed         : IndexedValue<AttestationValue<AttestationId.Device>>?        = null,
    val attestationIdProductIndexed        : IndexedValue<AttestationValue<AttestationId.Product>>?       = null,
    val attestationIdSerialIndexed         : IndexedValue<AttestationValue<AttestationId.Serial>>?        = null,
    val attestationIdImeiIndexed           : IndexedValue<AttestationValue<AttestationId.Imei>>?          = null,
    val attestationIdMeidIndexed           : IndexedValue<AttestationValue<AttestationId.Meid>>?          = null,
    val attestationIdManufacturerIndexed   : IndexedValue<AttestationValue<AttestationId.Manufacturer>>?  = null,
    val attestationIdModelIndexed          : IndexedValue<AttestationValue<AttestationId.Model>>?         = null,
    val vendorPatchLevelIndexed            : IndexedValue<AttestationValue<PatchLevel.Vendor>>?           = null,
    val bootPatchLevelIndexed              : IndexedValue<AttestationValue<PatchLevel.Boot>>?             = null,
    val deviceUniqueAttestationIndexed     : IndexedValue<AttestationValue<DeviceUniqueAttestation>>?     = null,
    val attestationIdSecondImeiIndexed     : IndexedValue<AttestationValue<AttestationId.SecondImei>>?    = null,
    val moduleHashIndexed                  : IndexedValue<AttestationValue<ModuleHash>>?                  = null,
    // @formatter:on
    val attestationVersion: Int? = null,
    val additionalProperties : List<Asn1Element> = emptyList()
) : Asn1Encodable<Asn1Sequence>, PrettyPrintable {
    /*   constructor(
           // @formatter:off
           purpose                     : Set<KeyPurpose>?             = null,
           algorithm                   : Algorithm?                   = null,
           keySize                     : KeySize?                     = null,
           digest                      : Set<Digest>?                 = null,
           padding                     : Set<Padding>?                = null,
           ecCurve                     : ECCurve?                     = null,
           rsaPublicExponent           : RsaPublicExponent?           = null,
           mgfDigest                   : Set<MgfDigest>?              = null,
           rollbackResistance          : RollbackResistance?          = null,
           earlyBootOnly               : EarlyBootOnly?               = null,
           activeDateTime              : ActiveDateTime?              = null,
           originationExpireDateTime   : OriginationExpireDateTime?   = null,
           usageExpireDateTime         : UsageExpireDateTime?         = null,
           usageCountLimit             : UsageCountLimit?             = null,
           noAuthRequired              : NoAuthRequired?              = null,
           userAuthType                : UserAuth?                    = null,
           authTimeout                 : AuthTimeout?                 = null,
           allowWhileOnBody            : AllowWhileOnBody?            = null,
           trustedUserPresenceRequired : TrustedUserPresenceRequired? = null,
           trustedConfirmationRequired : TrustedConfirmationRequired? = null,
           unlockedDeviceRequired      : UnlockedDeviceRequired?      = null,
           allApplications             : AllApplications?             = null,
           creationDateTime            : CreationDateTime?            = null,
           origin                      : Origin?                      = null,
           rollbackResistant           : RollbackResistent?           = null,
           rootOfTrust                 : RootOfTrust?                 = null,
           osVersion                   : OsVersion?                   = null,
           osPatchLevel                : OsPatchLevel?                = null,
           attestationApplicationId    : AttestationApplicationId?    = null,
           attestationIdBrand          : AttestationId.Brand?         = null,
           attestationIdDevice         : AttestationId.Device?        = null,
           attestationIdProduct        : AttestationId.Product?       = null,
           attestationIdSerial         : AttestationId.Serial?        = null,
           attestationIdImei           : AttestationId.Imei?          = null,
           attestationIdMeid           : AttestationId.Meid?          = null,
           attestationIdManufacturer   : AttestationId.Manufacturer?  = null,
           attestationIdModel          : AttestationId.Model?         = null,
           vendorPatchLevel            : PatchLevel.Vendor?           = null,
           bootPatchLevel              : PatchLevel.Boot?             = null,
           deviceUniqueAttestation     : DeviceUniqueAttestation?     = null,
           attestationIdSecondImei     : AttestationId.SecondImei?    = null,
           moduleHash                  : ModuleHash?                  = null,
           // @formatter:on
           attestationVersion: Int?
       ) : this(
           // @formatter:off
           purposeIndexed                     = purpose                    ?.map { AttestationValue.Success(it, KeyPurpose) }?.toSet(),
           algorithmIndexed                   = algorithm                  ?.let { AttestationValue.Success(it, Algorithm) },
           keySizeIndexed                     = keySize                    ?.let { AttestationValue.Success(it, KeySize) },
           digestIndexed                      = digest                     ?.map { AttestationValue.Success(it, Digest) }?.toSet(),
           paddingIndexed                     = padding                    ?.map { AttestationValue.Success(it, Padding) }?.toSet(),
           ecCurveIndexed                     = ecCurve                    ?.let { AttestationValue.Success(it, ECCurve) },
           rsaPublicExponentIndexed           = rsaPublicExponent          ?.let { AttestationValue.Success(it, RsaPublicExponent) },
           mgfDigestIndexed                   = mgfDigest                  ?.map { AttestationValue.Success(it, MgfDigest) }?.toSet(),
           rollbackResistanceIndexed          = rollbackResistance         ?.let { AttestationValue.Success(it, RollbackResistance) },
           earlyBootOnlyIndexed               = earlyBootOnly              ?.let { AttestationValue.Success(it, EarlyBootOnly) },
           activeDateTimeIndexed              = activeDateTime             ?.let { AttestationValue.Success(it, ActiveDateTime) },
           originationExpireDateTimeIndexed   = originationExpireDateTime  ?.let { AttestationValue.Success(it, OriginationExpireDateTime) },
           usageExpireDateTimeIndexed         = usageExpireDateTime        ?.let { AttestationValue.Success(it, UsageExpireDateTime) },
           usageCountLimitIndexed             = usageCountLimit            ?.let { AttestationValue.Success(it, UsageCountLimit) },
           noAuthRequiredIndexed              = noAuthRequired             ?.let { AttestationValue.Success(it, NoAuthRequired) },
           userAuthTypeIndexed                = userAuthType               ?.let { AttestationValue.Success(it, UserAuth) },
           authTimeoutIndexed                 = authTimeout                ?.let { AttestationValue.Success(it, AuthTimeout) },
           allowWhileOnBodyIndexed            = allowWhileOnBody           ?.let { AttestationValue.Success(it, AllowWhileOnBody) },
           trustedUserPresenceRequiredIndexed = trustedUserPresenceRequired?.let { AttestationValue.Success(it, TrustedUserPresenceRequired) },
           trustedConfirmationRequiredIndexed = trustedConfirmationRequired?.let { AttestationValue.Success(it, TrustedConfirmationRequired) },
           unlockedDeviceRequiredIndexed      = unlockedDeviceRequired     ?.let { AttestationValue.Success(it, UnlockedDeviceRequired) },
           allApplicationsIndexed             = allApplications            ?.let { AttestationValue.Success(it, AllApplications) },
           creationDateTimeIndexed            = creationDateTime           ?.let { AttestationValue.Success(it, CreationDateTime) },
           originIndexed                      = origin                     ?.let { AttestationValue.Success(it, Origin) },
           rollbackResistantIndexed           = rollbackResistant          ?.let { AttestationValue.Success(it, RollbackResistent) },
           rootOfTrustIndexed                 = rootOfTrust                ?.let { AttestationValue.Success(it, RootOfTrust) },
           osVersionIndexed                   = osVersion                  ?.let { AttestationValue.Success(it, OsVersion) },
           osPatchLevelIndexed                = osPatchLevel               ?.let { AttestationValue.Success(it, OsPatchLevel) },
           attestationApplicationIdIndexed    = attestationApplicationId   ?.let { AttestationValue.Success(it, AttestationApplicationId) },
           attestationIdBrandIndexed          = attestationIdBrand         ?.let { AttestationValue.Success(it, AttestationId.Brand) },
           attestationIdDeviceIndexed         = attestationIdDevice        ?.let { AttestationValue.Success(it, AttestationId.Device) },
           attestationIdProductIndexed        = attestationIdProduct       ?.let { AttestationValue.Success(it, AttestationId.Product) },
           attestationIdSerialIndexed         = attestationIdSerial        ?.let { AttestationValue.Success(it, AttestationId.Serial) },
           attestationIdImeiIndexed           = attestationIdImei          ?.let { AttestationValue.Success(it, AttestationId.Imei) },
           attestationIdMeidIndexed           = attestationIdMeid          ?.let { AttestationValue.Success(it, AttestationId.Meid) },
           attestationIdManufacturerIndexed   = attestationIdManufacturer  ?.let { AttestationValue.Success(it, AttestationId.Manufacturer) },
           attestationIdModelIndexed          = attestationIdModel         ?.let { AttestationValue.Success(it, AttestationId.Model) },
           vendorPatchLevelIndexed            = vendorPatchLevel           ?.let { AttestationValue.Success(it, PatchLevel.Vendor) },
           bootPatchLevelIndexed              = bootPatchLevel             ?.let { AttestationValue.Success(it, PatchLevel.Boot) },
           deviceUniqueAttestationIndexed     = deviceUniqueAttestation    ?.let { AttestationValue.Success(it, DeviceUniqueAttestation) },
           attestationIdSecondImeiIndexed     = attestationIdSecondImei    ?.let { AttestationValue.Success(it, AttestationId.SecondImei) },
           moduleHashIndexed                  = moduleHash                 ?.let { AttestationValue.Success(it, ModuleHash) },
           // @formatter:on
       )*/

    val purpose: Set<AttestationValue<KeyPurpose>>? get() = purposeIndexed?.value
    val algorithm: AttestationValue<Algorithm>? get() = algorithmIndexed?.value
    val keySize: AttestationValue<KeySize>? get() = keySizeIndexed?.value
    val digest: Set<AttestationValue<Digest>>? get() = digestIndexed?.value
    val padding: Set<AttestationValue<Padding>>? get() = paddingIndexed?.value
    val ecCurve: AttestationValue<ECCurve>? get() = ecCurveIndexed?.value
    val rsaPublicExponent: AttestationValue<RsaPublicExponent>? get() = rsaPublicExponentIndexed?.value
    val mgfDigest: Set<AttestationValue<MgfDigest>>? get() = mgfDigestIndexed?.value
    val rollbackResistance: AttestationValue<RollbackResistance>? get() = rollbackResistanceIndexed?.value
    val earlyBootOnly: AttestationValue<EarlyBootOnly>? get() = earlyBootOnlyIndexed?.value
    val activeDateTime: AttestationValue<ActiveDateTime>? get() = activeDateTimeIndexed?.value
    val originationExpireDateTime: AttestationValue<OriginationExpireDateTime>? get() = originationExpireDateTimeIndexed?.value
    val usageExpireDateTime: AttestationValue<UsageExpireDateTime>? get() = usageExpireDateTimeIndexed?.value
    val usageCountLimit: AttestationValue<UsageCountLimit>? get() = usageCountLimitIndexed?.value
    val noAuthRequired: AttestationValue<NoAuthRequired>? get() = noAuthRequiredIndexed?.value
    val userAuthType: AttestationValue<UserAuth>? get() = userAuthTypeIndexed?.value
    val authTimeout: AttestationValue<AuthTimeout>? get() = authTimeoutIndexed?.value
    val allowWhileOnBody: AttestationValue<AllowWhileOnBody>? get() = allowWhileOnBodyIndexed?.value
    val trustedUserPresenceRequired: AttestationValue<TrustedUserPresenceRequired>? get() = trustedUserPresenceRequiredIndexed?.value
    val trustedConfirmationRequired: AttestationValue<TrustedConfirmationRequired>? get() = trustedConfirmationRequiredIndexed?.value
    val unlockedDeviceRequired: AttestationValue<UnlockedDeviceRequired>? get() = unlockedDeviceRequiredIndexed?.value
    val allApplications: AttestationValue<AllApplications>? get() = allApplicationsIndexed?.value // only up to version v4 // TODO add opt-in annotation?
    val creationDateTime: AttestationValue<CreationDateTime>? get() = creationDateTimeIndexed?.value
    val origin: AttestationValue<Origin>? get() = originIndexed?.value
    val rollbackResistant: AttestationValue<RollbackResistent>? get() = rollbackResistantIndexed?.value // only up to version v2, "resistance" afterwards // TODO add opt-in annotation?
    val rootOfTrust: AttestationValue<RootOfTrust>? get() = rootOfTrustIndexed?.value
    val osVersion: AttestationValue<OsVersion>? get() = osVersionIndexed?.value
    val osPatchLevel: AttestationValue<OsPatchLevel>? get() = osPatchLevelIndexed?.value
    val attestationApplicationId: AttestationValue<AttestationApplicationId>? get() = attestationApplicationIdIndexed?.value
    val attestationIdBrand: AttestationValue<AttestationId.Brand>? get() = attestationIdBrandIndexed?.value
    val attestationIdDevice: AttestationValue<AttestationId.Device>? get() = attestationIdDeviceIndexed?.value
    val attestationIdProduct: AttestationValue<AttestationId.Product>? get() = attestationIdProductIndexed?.value
    val attestationIdSerial: AttestationValue<AttestationId.Serial>? get() = attestationIdSerialIndexed?.value
    val attestationIdImei: AttestationValue<AttestationId.Imei>? get() = attestationIdImeiIndexed?.value
    val attestationIdMeid: AttestationValue<AttestationId.Meid>? get() = attestationIdMeidIndexed?.value
    val attestationIdManufacturer: AttestationValue<AttestationId.Manufacturer>? get() = attestationIdManufacturerIndexed?.value
    val attestationIdModel: AttestationValue<AttestationId.Model>? get() = attestationIdModelIndexed?.value
    val vendorPatchLevel: AttestationValue<PatchLevel.Vendor>? get() = vendorPatchLevelIndexed?.value
    val bootPatchLevel: AttestationValue<PatchLevel.Boot>? get() = bootPatchLevelIndexed?.value
    val deviceUniqueAttestation: AttestationValue<DeviceUniqueAttestation>? get() = deviceUniqueAttestationIndexed?.value
    val attestationIdSecondImei: AttestationValue<AttestationId.SecondImei>? get() = attestationIdSecondImeiIndexed?.value
    val moduleHash: AttestationValue<ModuleHash>? get() = moduleHashIndexed?.value
    // @formatter:on

    val indexedProperties: List<IndexedValue<*>>
        get() = buildList {
            purposeIndexed?.let { add(it) }
            algorithmIndexed?.let { add(it) }
            keySizeIndexed?.let { add(it) }
            digestIndexed?.let { add(it) }
            paddingIndexed?.let { add(it) }
            ecCurveIndexed?.let { add(it) }
            rsaPublicExponentIndexed?.let { add(it) }
            mgfDigestIndexed?.let { add(it) }
            rollbackResistanceIndexed?.let { add(it) }
            earlyBootOnlyIndexed?.let { add(it) }
            activeDateTimeIndexed?.let { add(it) }
            originationExpireDateTimeIndexed?.let { add(it) }
            usageExpireDateTimeIndexed?.let { add(it) }
            usageCountLimitIndexed?.let { add(it) }
            noAuthRequiredIndexed?.let { add(it) }
            userAuthTypeIndexed?.let { add(it) }
            authTimeoutIndexed?.let { add(it) }
            allowWhileOnBodyIndexed?.let { add(it) }
            trustedUserPresenceRequiredIndexed?.let { add(it) }
            trustedConfirmationRequiredIndexed?.let { add(it) }
            unlockedDeviceRequiredIndexed?.let { add(it) }
            allApplicationsIndexed?.let { add(it) }
            creationDateTimeIndexed?.let { add(it) }
            originIndexed?.let { add(it) }
            rollbackResistantIndexed?.let { add(it) }
            rootOfTrustIndexed?.let { add(it) }
            osVersionIndexed?.let { add(it) }
            osPatchLevelIndexed?.let { add(it) }
            attestationApplicationIdIndexed?.let { add(it) }
            attestationIdBrandIndexed?.let { add(it) }
            attestationIdDeviceIndexed?.let { add(it) }
            attestationIdProductIndexed?.let { add(it) }
            attestationIdSerialIndexed?.let { add(it) }
            attestationIdImeiIndexed?.let { add(it) }
            attestationIdMeidIndexed?.let { add(it) }
            attestationIdManufacturerIndexed?.let { add(it) }
            attestationIdModelIndexed?.let { add(it) }
            vendorPatchLevelIndexed?.let { add(it) }
            bootPatchLevelIndexed?.let { add(it) }
            deviceUniqueAttestationIndexed?.let { add(it) }
            attestationIdSecondImeiIndexed?.let { add(it) }
            moduleHashIndexed?.let { add(it) }
        }


    init {
        purpose?.let { require(it.isNotEmpty()) }
        digest?.let { require(it.isNotEmpty()) }
        padding?.let { require(it.isNotEmpty()) }
        mgfDigest?.let { require(it.isNotEmpty()) }

        //versionCheck()
    }

    /**
     * Useful for debugging, but too strict in reality
     */
    fun versionCheck() {
        if (attestationVersion != null) {
            if (attestationVersion < 400) {
                require(moduleHash == null)
            }
            if (attestationVersion < 300) {
                require(attestationIdSecondImei == null)
            }
            // no changes from 100 to 200
            if (attestationVersion < 100) {
                require(mgfDigest == null) // isNullOrEmpty ? TODO
                require(usageCountLimit == null)
            }
            if (attestationVersion > 4) {
                require(allApplications == null)
            }
            if (attestationVersion < 4) {
                require(earlyBootOnly == null)
                require(deviceUniqueAttestation == null)
            }
            if (attestationVersion < 3) {
                require(rollbackResistance == null)
                require(trustedUserPresenceRequired == null)
                require(trustedConfirmationRequired == null)
                require(unlockedDeviceRequired == null)
                require(vendorPatchLevel == null)
                require(bootPatchLevel == null)
                //if(rootOfTrust != null) require(rootOfTrust.getOrNull().verifiedBootHash == 0) // TODO decoding must be changed!!
            }
            if (attestationVersion > 2) {
                require(rollbackResistant == null)
            }
            if (attestationVersion < 2) {
                require(attestationApplicationId == null)
                require(attestationIdBrand == null)
                require(attestationIdDevice == null)
                require(attestationIdProduct == null)
                require(attestationIdSerial == null)
                require(attestationIdImei == null)
                require(attestationIdMeid == null)
                require(attestationIdManufacturer == null)
                require(attestationIdModel == null)
            }
        }
        // TODO: only provide getter in right versions?
    }

    override fun encodeToTlv() = Asn1.Sequence {

        indexedProperties.sortedBy { (index, _) -> index }.forEach { (_, value) ->
            when (value) {

                is AttestationValue<*> -> add(value)

                is Set<*> -> add(value as Set<AttestationValue<*>>)
            }
        }

        additionalProperties.forEach {
            +it
        }

    }

    companion object : Asn1Decodable<Asn1Sequence, AuthorizationList> {
        override fun doDecode(src: Asn1Sequence): AuthorizationList {
            val src= TrackingSequence(src)
            // @formatter:off
            val purpose                    : IndexedValue<Set<AttestationValue<KeyPurpose>>>?             = KeyPurpose.decodeSet(src)
            val algorithm                  : IndexedValue<AttestationValue<Algorithm>>?                   = Algorithm.decode(src)
            val keySize                    : IndexedValue<AttestationValue<KeySize>>?                     = KeySize.decode(src)
            val digest                     : IndexedValue<Set<AttestationValue<Digest>>>?                 = Digest.decodeSet(src)
            val padding                    : IndexedValue<Set<AttestationValue<Padding>>>?                = Padding.decodeSet(src)
            val ecCurve                    : IndexedValue<AttestationValue<ECCurve>>?                     = ECCurve.decode(src)
            val rsaPublicExponent          : IndexedValue<AttestationValue<RsaPublicExponent>>?           = RsaPublicExponent.decode(src)
            val mgfDigest                  : IndexedValue<Set<AttestationValue<MgfDigest>>>?              = MgfDigest.decodeSet(src)
            val rollbackResistance         : IndexedValue<AttestationValue<RollbackResistance>>?          = RollbackResistance.decodeNull(src)
            val earlyBootOnly              : IndexedValue<AttestationValue<EarlyBootOnly>>?               = EarlyBootOnly.decodeNull(src)
            val activeDateTime             : IndexedValue<AttestationValue<ActiveDateTime>>?              = ActiveDateTime.decode(src)
            val originationExpireDateTime  : IndexedValue<AttestationValue<OriginationExpireDateTime>>?   = OriginationExpireDateTime.decode(src)
            val usageExpireDateTime        : IndexedValue<AttestationValue<UsageExpireDateTime>>?         = UsageExpireDateTime.decode(src)
            val usageCountLimit            : IndexedValue<AttestationValue<UsageCountLimit>>?             = UsageCountLimit.decode(src)
            val noAuthRequired             : IndexedValue<AttestationValue<NoAuthRequired>>?              = NoAuthRequired.decodeNull(src)
            val userAuthType               : IndexedValue<AttestationValue<UserAuth>>?                    = UserAuth.decode(src)
            val authTimeout                : IndexedValue<AttestationValue<AuthTimeout>>?                 = AuthTimeout.decode(src)
            val allowWhileOnBody           : IndexedValue<AttestationValue<AllowWhileOnBody>>?            = AllowWhileOnBody.decodeNull(src)
            val trustedUserPresenceRequired: IndexedValue<AttestationValue<TrustedUserPresenceRequired>>? = TrustedUserPresenceRequired.decodeNull(src)
            val trustedConfirmationRequired: IndexedValue<AttestationValue<TrustedConfirmationRequired>>? = TrustedConfirmationRequired.decodeNull(src)
            val unlockedDeviceRequired     : IndexedValue<AttestationValue<UnlockedDeviceRequired>>?      = UnlockedDeviceRequired.decodeNull(src)
            val allApplications            : IndexedValue<AttestationValue<AllApplications>>?             = AllApplications.decodeNull(src)
            val creationDateTime           : IndexedValue<AttestationValue<CreationDateTime>>?            = CreationDateTime.decode(src)
            val origin                     : IndexedValue<AttestationValue<Origin>>?                      = Origin.decode(src)
            val rollbackResistant          : IndexedValue<AttestationValue<RollbackResistent>>?           = RollbackResistent.decodeNull(src)
            // @formatter:on

            val rootOfTrust: IndexedValue<AttestationValue<RootOfTrust>>? =
                src[RootOfTrust.explicitTag]?.let { (index, rot) ->
                    RootOfTrust.decodeFromTlvSafe(rot.asSequence()).fold(
                        onSuccess = { AttestationValue.Success(it, RootOfTrust) },
                        onFailure = {
                            AttestationValue.Failure(
                                RootOfTrust::class.simpleName!!,
                                RootOfTrust,
                                rot
                            ) as AttestationValue<RootOfTrust>
                        }).let { IndexedValue(index, it) }
                }
            val osVersion: IndexedValue<AttestationValue<OsVersion>>? = OsVersion.decode(src)
            val osPatchLevel: IndexedValue<AttestationValue<OsPatchLevel>>? = OsPatchLevel.decode(src)
            val attestationApplicationId: IndexedValue<AttestationValue<AttestationApplicationId>>? =
                AttestationApplicationId.decode(src)

            // @formatter:off
            val attestationIdBrand       : IndexedValue<AttestationValue<AttestationId.Brand>>?          = AttestationId.Brand.decode(src)
            val attestationIdDevice      : IndexedValue<AttestationValue<AttestationId.Device>>?         = AttestationId.Device.decode(src)
            val attestationIdProduct     : IndexedValue<AttestationValue<AttestationId.Product>>?        = AttestationId.Product.decode(src)
            val attestationIdSerial      : IndexedValue<AttestationValue<AttestationId.Serial>>?         = AttestationId.Serial.decode(src)
            val attestationIdImei        : IndexedValue<AttestationValue<AttestationId.Imei>>?           = AttestationId.Imei.decode(src)
            val attestationIdMeid        : IndexedValue<AttestationValue<AttestationId.Meid>>?           = AttestationId.Meid.decode(src)
            val attestationIdManufacturer: IndexedValue<AttestationValue<AttestationId.Manufacturer>>?   = AttestationId.Manufacturer.decode(src)
            val attestationIdModel       : IndexedValue<AttestationValue<AttestationId.Model>>?          = AttestationId.Model.decode(src)
            val vendorPatchLevel         : IndexedValue<AttestationValue<PatchLevel.Vendor>>?            = PatchLevel.Vendor.decode(src)
            val bootPatchLevel           : IndexedValue<AttestationValue<PatchLevel.Boot>>?              = PatchLevel.Boot.decode(src)
            val deviceUniqueAttestation  : IndexedValue<AttestationValue<DeviceUniqueAttestation>>?      = DeviceUniqueAttestation.decodeNull(src)
            val attestationIdSecondImei  : IndexedValue<AttestationValue<AttestationId.SecondImei>>?     = AttestationId.SecondImei.decode(src)
            val moduleHash               : IndexedValue<AttestationValue<ModuleHash>>?                   = ModuleHash.decode(src)
            // @formatter:on

            return AuthorizationList(
                purpose,
                algorithm,
                keySize,
                digest,
                padding,
                ecCurve,
                rsaPublicExponent,
                mgfDigest,
                rollbackResistance,
                earlyBootOnly,
                activeDateTime,
                originationExpireDateTime,
                usageExpireDateTime,
                usageCountLimit,
                noAuthRequired,
                userAuthType,
                authTimeout,
                allowWhileOnBody,
                trustedUserPresenceRequired,
                trustedConfirmationRequired,
                unlockedDeviceRequired,
                allApplications,
                creationDateTime,
                origin,
                rollbackResistant,
                rootOfTrust,
                osVersion,
                osPatchLevel,
                attestationApplicationId,
                attestationIdBrand,
                attestationIdDevice,
                attestationIdProduct,
                attestationIdSerial,
                attestationIdImei,
                attestationIdMeid,
                attestationIdManufacturer,
                attestationIdModel,
                vendorPatchLevel,
                bootPatchLevel,
                deviceUniqueAttestation,
                attestationIdSecondImei,
                moduleHash,
                additionalProperties = src.retainUnread()
            )
        }

        // TODO: check decode functions once more
        private inline fun <reified T : Tagged, reified D : Asn1Encodable<Asn1Element>> T.decode(src: TrackingSequence): IndexedValue<AttestationValue<D>>? =
            src[explicitTag]?.let { (index, element) ->
                @Suppress("UNCHECKED_CAST")
                (this as Asn1Decodable<Asn1Element, D>).decodeFromTlvSafe(src = element).fold(
                    onSuccess = { AttestationValue.Success(it, this) },
                    onFailure = {
                        AttestationValue.Failure(
                            D::class.simpleName!!,
                            this,
                            element
                        ) as AttestationValue<D>
                    }).let { IndexedValue(index, it) }
            }

        private inline fun <reified T : Tagged, reified D : Asn1Encodable<Asn1Element>> T.decodeSet(
            src: TrackingSequence
        ): IndexedValue<Set<AttestationValue<D>>>? = src[explicitTag]?.let { (index, it) ->
            @Suppress("UNCHECKED_CAST")
            ((it as Asn1Set).children.map { child ->

                (this as Asn1Decodable<Asn1Element, D>).decodeFromTlvSafe(
                    child.asPrimitive()
                ).fold(
                    onSuccess = { AttestationValue.Success(it, this) },
                    onFailure = { AttestationValue.Failure(D::class.simpleName!!, this, child) })
            }.toSet()
                .let { it.ifEmpty { null } } as Set<AttestationValue<D>>?)?.let {
                IndexedValue(
                    index,
                    it
                )
            } // TODO isEmpty -> null? << do we really want null instead of empty sets? rather use empty set
        }

        private inline fun <reified T : Tagged, reified D : Asn1Encodable<Asn1Element>> T.decodeSequence(
            src: TrackingSequence
        ): List<KmmResult<D>>? = src[explicitTag]?.let {
            @Suppress("UNCHECKED_CAST")
            (it as Asn1Sequence).children.mapNotNull {
                (this as Asn1Decodable<Asn1Element, D>).decodeFromTlvSafe(
                    it.asPrimitive()
                )
            }.toList().let { if (it.isEmpty()) null else it }
        }

        private operator fun TrackingSequence.get(tag: ULong): IndexedValue<Asn1Element>? {
            val asn1Tag = Asn1.ExplicitTag(tag)
            val found = src.children.withIndex().firstOrNull { (it.value as Asn1ExplicitlyTagged).tag == asn1Tag }
                ?.let { (index, value) -> IndexedValue(index, value as Asn1ExplicitlyTagged) }
            return found?.value?.children?.singleOrNull?.let { IndexedValue(found.index, it) }?.apply { markExtracted(asn1Tag)}
        }


        private inline fun <reified A : Asn1Encodable<Asn1Primitive>> A.decodeNull(src: TrackingSequence): IndexedValue<AttestationValue<A>>? {
            val tag = (this as Tagged).explicitTag
            val asn1Tag = Asn1.ExplicitTag(tag)
            val indexedFound =
                src.src.children.withIndex().firstOrNull { (it.value as Asn1ExplicitlyTagged).tag == asn1Tag }
                    ?: return null

            return ((indexedFound.value as Asn1ExplicitlyTagged?)?.children)?.let {
                if (it.isEmpty()) return@let null
                (if (it.size != 1) AttestationValue.Failure(this::class.simpleName!!, this, src.src)
                else {
                    val first = it.first()
                    catchingUnwrapped { first.asPrimitive().readNull() }
                        .fold(
                            onSuccess = { AttestationValue.Success(this, this) },
                            onFailure = { AttestationValue.Failure(this::class.simpleName!!, this, first) })
                })
            }.let { IndexedValue(indexedFound.index, it) as IndexedValue<AttestationValue<A>>? }.apply { src.markExtracted(asn1Tag) }
        }

        private val List<Asn1Element>.singleOrNull: Asn1Element? get() = if (size == 1) first() else null
    }

    private fun Asn1TreeBuilder.add(element: Set<Tagged.WithTag<*>>?) {
        element?.let { +it.encode() }
    }

    private fun Asn1TreeBuilder.add(element: Tagged.WithTag<*>?) {
        element?.let { +Asn1.ExplicitlyTagged(it.tagged.explicitTag) { +it.encodeToTlv() } }
    }

    private fun Asn1TreeBuilder.add(element: Tagged?) {
        element?.let { +Asn1.ExplicitlyTagged(it.explicitTag) { +Asn1.Null() } }
    }

    private val Set<Tagged.WithTag<*>>.explicitTag get() = first().tagged.explicitTag
    private fun Set<Tagged.WithTag<*>>.encode() = Asn1.ExplicitlyTagged(explicitTag) {
        +Asn1.SetOf { forEach { +it } }

    }


    @OptIn(ExperimentalStdlibApi::class)
    override fun toString(): String {
        return "AuthorizationList(" +
                "purpose=$purpose, " +
                "algorithm=$algorithm, " +
                "keySize=$keySize, " +
                "digest=$digest, " +
                "padding=$padding, " +
                "ecCurve=$ecCurve, " +
                "rsaPublicExponent=$rsaPublicExponent, " +
                "mgfDigest=$mgfDigest, " +
                "rollbackResistance=${rollbackResistance != null}, " +
                "earlyBootOnly=${earlyBootOnly != null}, " +
                "activeDateTime=$activeDateTime, " +
                "originationExpireDateTime=$originationExpireDateTime, " +
                "usageExpireDateTime=$usageExpireDateTime, " +
                "usageCountLimit=$usageCountLimit, " +
                "noAuthRequired=${noAuthRequired != null}, " +
                "userAuthType=$userAuthType, " +
                "authTimeout=$authTimeout, " +
                "allowWhileOnBody=${allowWhileOnBody != null}, " +
                "trustedUserPresenceRequired=${trustedUserPresenceRequired != null}, " +
                "trustedConfirmationRequired=${trustedConfirmationRequired != null}, " +
                "unlockedDeviceRequired=${unlockedDeviceRequired != null}, " +
                "allApplications=${allApplications != null}, " +
                "creationDateTime=$creationDateTime, " +
                "origin=$origin, " +
                "rollbackResistant=$rollbackResistant, " +
                "rootOfTrust=$rootOfTrust, " +
                "osVersion=$osVersion, " +
                "osPatchLevel=$osPatchLevel, " +
                "attestationApplicationId=$attestationApplicationId, " +
                "attestationIdBrand=$attestationIdBrand, " +
                "attestationIdDevice=$attestationIdDevice, " +
                "attestationIdProduct=$attestationIdProduct, " +
                "attestationIdSerial=$attestationIdSerial, " +
                "attestationIdImei=$attestationIdImei, " +
                "attestationIdMeid=$attestationIdMeid, " +
                "attestationIdManufacturer=$attestationIdManufacturer, " +
                "attestationIdModel=$attestationIdModel, " +
                "vendorPatchLevel=$vendorPatchLevel, " +
                "bootPatchLevel=$bootPatchLevel, " +
                "deviceUniqueAttestation=${deviceUniqueAttestation != null}, " +
                "attestationIdSecondImei=$attestationIdSecondImei, " +
                "moduleHash=$moduleHash" +
                ")"
    }

    // AuthorizationList.prettyPrint
    @OptIn(ExperimentalStdlibApi::class)
    override fun doPrettyPrint(indent: String): String {
        val fieldIndent = indent + "  "
        val valueIndent = indent + "    "

        fun AttestationValue<*>.render(indent: String): String = doPrettyPrint(indent)

        fun StringBuilder.appendSingle(name: String, value: AttestationValue<*>?) {
            append(fieldIndent).append(name).append(" = ")
            if (value == null) {
                append("null\n")
                return
            }

            // try inline if it renders to a single line
            val rendered = value.render(valueIndent)
            val lines = rendered.lines()
            if (lines.size == 1) {
                append(lines.first().trimStart()).append('\n')
            } else {
                append('\n')
                append(rendered).append('\n')
            }
        }

        fun StringBuilder.appendSet(name: String, values: Set<AttestationValue<*>>?) {
            append(fieldIndent).append(name).append(" = ")
            if (values.isNullOrEmpty()) {
                append("null\n")
                return
            }
            append("[\n")
            values.forEach { v ->
                val rendered = v.render(valueIndent)
                val lines = rendered.lines()
                if (lines.size == 1) {
                    append(valueIndent).append("- ").append(lines.first().trimStart()).append('\n')
                } else {
                    append(valueIndent).append("-\n")
                    append(rendered).append('\n')
                }
            }
            append(fieldIndent).append("]\n")
        }

        fun StringBuilder.appendBool(name: String, present: Boolean) {
            append(fieldIndent).append(name).append(" = ").append(present).append('\n')
        }

        return buildString {
            append(indent).append("AuthorizationList(\n")

            appendSet("purpose", purpose as Set<AttestationValue<*>>?)
            appendSingle("algorithm", algorithm)
            appendSingle("keySize", keySize)
            appendSet("digest", digest as Set<AttestationValue<*>>?)
            appendSet("padding", padding as Set<AttestationValue<*>>?)
            appendSingle("ecCurve", ecCurve)
            appendSingle("rsaPublicExponent", rsaPublicExponent)
            appendSet("mgfDigest", mgfDigest as Set<AttestationValue<*>>?)

            appendBool("rollbackResistance", rollbackResistance != null)
            appendBool("earlyBootOnly", earlyBootOnly != null)

            appendSingle("activeDateTime", activeDateTime)
            appendSingle("originationExpireDateTime", originationExpireDateTime)
            appendSingle("usageExpireDateTime", usageExpireDateTime)
            appendSingle("usageCountLimit", usageCountLimit)

            appendBool("noAuthRequired", noAuthRequired != null)

            appendSingle("userAuthType", userAuthType)
            appendSingle("authTimeout", authTimeout)

            appendBool("allowWhileOnBody", allowWhileOnBody != null)
            appendBool("trustedUserPresenceRequired", trustedUserPresenceRequired != null)
            appendBool("trustedConfirmationRequired", trustedConfirmationRequired != null)
            appendBool("unlockedDeviceRequired", unlockedDeviceRequired != null)
            appendBool("allApplications", allApplications != null)

            appendSingle("creationDateTime", creationDateTime)
            appendSingle("origin", origin)

            appendSingle("rollbackResistant", rollbackResistant)
            appendSingle("rootOfTrust", rootOfTrust)
            appendSingle("osVersion", osVersion)
            appendSingle("osPatchLevel", osPatchLevel)
            appendSingle("attestationApplicationId", attestationApplicationId)

            appendSingle("attestationIdBrand", attestationIdBrand)
            appendSingle("attestationIdDevice", attestationIdDevice)
            appendSingle("attestationIdProduct", attestationIdProduct)
            appendSingle("attestationIdSerial", attestationIdSerial)
            appendSingle("attestationIdImei", attestationIdImei)
            appendSingle("attestationIdMeid", attestationIdMeid)
            appendSingle("attestationIdManufacturer", attestationIdManufacturer)
            appendSingle("attestationIdModel", attestationIdModel)

            appendSingle("vendorPatchLevel", vendorPatchLevel)
            appendSingle("bootPatchLevel", bootPatchLevel)

            appendBool("deviceUniqueAttestation", deviceUniqueAttestation != null)

            appendSingle("attestationIdSecondImei", attestationIdSecondImei)
            appendSingle("moduleHash", moduleHash)

            append(indent).append(")")
        }
    }


    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AuthorizationList) return false

        if (purpose != other.purpose) return false
        if (algorithm != other.algorithm) return false
        if (keySize != other.keySize) return false
        if (digest != other.digest) return false
        if (padding != other.padding) return false
        if (ecCurve != other.ecCurve) return false
        if (rsaPublicExponent != other.rsaPublicExponent) return false
        if (mgfDigest != other.mgfDigest) return false
        if (rollbackResistance != other.rollbackResistance) return false
        if (earlyBootOnly != other.earlyBootOnly) return false
        if (activeDateTime != other.activeDateTime) return false
        if (originationExpireDateTime != other.originationExpireDateTime) return false
        if (usageExpireDateTime != other.usageExpireDateTime) return false
        if (usageCountLimit != other.usageCountLimit) return false
        if (noAuthRequired != other.noAuthRequired) return false
        if (userAuthType != other.userAuthType) return false
        if (authTimeout != other.authTimeout) return false
        if (allowWhileOnBody != other.allowWhileOnBody) return false
        if (trustedUserPresenceRequired != other.trustedUserPresenceRequired) return false
        if (trustedConfirmationRequired != other.trustedConfirmationRequired) return false
        if (unlockedDeviceRequired != other.unlockedDeviceRequired) return false
        if (allApplications != other.allApplications) return false
        if (creationDateTime != other.creationDateTime) return false
        if (origin != other.origin) return false
        if (rollbackResistant != other.rollbackResistant) return false
        if (rootOfTrust != other.rootOfTrust) return false
        if (osVersion != other.osVersion) return false
        if (osPatchLevel != other.osPatchLevel) return false
        if (attestationApplicationId != other.attestationApplicationId) return false
        if (attestationIdBrand != other.attestationIdBrand) return false
        if (attestationIdDevice != other.attestationIdDevice) return false
        if (attestationIdProduct != other.attestationIdProduct) return false
        if (attestationIdSerial != other.attestationIdSerial) return false
        if (attestationIdImei != other.attestationIdImei) return false
        if (attestationIdMeid != other.attestationIdMeid) return false
        if (attestationIdManufacturer != other.attestationIdManufacturer) return false
        if (attestationIdModel != other.attestationIdModel) return false
        if (vendorPatchLevel != other.vendorPatchLevel) return false
        if (bootPatchLevel != other.bootPatchLevel) return false
        if (deviceUniqueAttestation != other.deviceUniqueAttestation) return false
        if (attestationIdSecondImei != other.attestationIdSecondImei) return false
        if (moduleHash != other.moduleHash) return false

        return true
    }

    override fun hashCode(): Int {
        var result = purpose?.hashCode() ?: 0
        result = 31 * result + (algorithm?.hashCode() ?: 0)
        result = 31 * result + (keySize?.hashCode() ?: 0)
        result = 31 * result + (digest?.hashCode() ?: 0)
        result = 31 * result + (padding?.hashCode() ?: 0)
        result = 31 * result + (ecCurve?.hashCode() ?: 0)
        result = 31 * result + (rsaPublicExponent?.hashCode() ?: 0)
        result = 31 * result + (mgfDigest?.hashCode() ?: 0)
        result = 31 * result + (rollbackResistance?.hashCode() ?: 0)
        result = 31 * result + (earlyBootOnly?.hashCode() ?: 0)
        result = 31 * result + (activeDateTime?.hashCode() ?: 0)
        result = 31 * result + (originationExpireDateTime?.hashCode() ?: 0)
        result = 31 * result + (usageExpireDateTime?.hashCode() ?: 0)
        result = 31 * result + (usageCountLimit?.hashCode() ?: 0)
        result = 31 * result + (noAuthRequired?.hashCode() ?: 0)
        result = 31 * result + (userAuthType?.hashCode() ?: 0)
        result = 31 * result + (authTimeout?.hashCode() ?: 0)
        result = 31 * result + (allowWhileOnBody?.hashCode() ?: 0)
        result = 31 * result + (trustedUserPresenceRequired?.hashCode() ?: 0)
        result = 31 * result + (trustedConfirmationRequired?.hashCode() ?: 0)
        result = 31 * result + (unlockedDeviceRequired?.hashCode() ?: 0)
        result = 31 * result + (allApplications?.hashCode() ?: 0)
        result = 31 * result + (creationDateTime?.hashCode() ?: 0)
        result = 31 * result + (origin?.hashCode() ?: 0)
        result = 31 * result + (rollbackResistant?.hashCode() ?: 0)
        result = 31 * result + (rootOfTrust?.hashCode() ?: 0)
        result = 31 * result + (osVersion?.hashCode() ?: 0)
        result = 31 * result + (osPatchLevel?.hashCode() ?: 0)
        result = 31 * result + (attestationApplicationId?.hashCode() ?: 0)
        result = 31 * result + (attestationIdBrand?.hashCode() ?: 0)
        result = 31 * result + (attestationIdDevice?.hashCode() ?: 0)
        result = 31 * result + (attestationIdProduct?.hashCode() ?: 0)
        result = 31 * result + (attestationIdSerial?.hashCode() ?: 0)
        result = 31 * result + (attestationIdImei?.hashCode() ?: 0)
        result = 31 * result + (attestationIdMeid?.hashCode() ?: 0)
        result = 31 * result + (attestationIdManufacturer?.hashCode() ?: 0)
        result = 31 * result + (attestationIdModel?.hashCode() ?: 0)
        result = 31 * result + (vendorPatchLevel?.hashCode() ?: 0)
        result = 31 * result + (bootPatchLevel?.hashCode() ?: 0)
        result = 31 * result + (deviceUniqueAttestation?.hashCode() ?: 0)
        result = 31 * result + (attestationIdSecondImei?.hashCode() ?: 0)
        result = 31 * result + (moduleHash?.hashCode() ?: 0)
        return result
    }

    interface IntEncodable : Asn1Encodable<Asn1Primitive>, Tagged.WithTag<Asn1Primitive> {
        val intValue: Asn1Integer

        override fun encodeToTlv() = intValue.encodeToTlv()
    }

    sealed class Tagged(val explicitTag: ULong) {
        sealed interface WithTag<A : Asn1Element> : Asn1Encodable<A> {
            val tagged: Tagged
        }
    }

    enum class KeyPurpose(override val intValue: Asn1Integer) : IntEncodable {
        ENCRYPT(Asn1Integer(0)),
        DECRYPT(Asn1Integer(1)),
        SIGN(Asn1Integer(2)),
        VERIFY(Asn1Integer(3)),
        DERIVE_KEY(Asn1Integer(4)), // according to aidl specification: "4 is reserved", note: not in reference implementation // TODO
        WRAP_KEY(Asn1Integer(5)),
        AGREE_KEY(Asn1Integer(6)),
        ATTEST_KEY(Asn1Integer(7));
        // From: https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/android/hardware/security/keymint/KeyPurpose.aidl

        companion object Tag : Tagged(1uL), Asn1Decodable<Asn1Primitive, KeyPurpose> {
            fun valueOf(int: Asn1Integer) = entries.first { it.intValue == int }
            override fun doDecode(src: Asn1Primitive) = valueOf(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    enum class Algorithm(override val intValue: Asn1Integer) : IntEncodable {
        RSA(Asn1Integer(1)),

        //@HazardousMaterials("according to aidl specification: removed, do not reuse.") DSA(Asn1Integer(2)), // TODO: comment in for BasicParsingTests to fail
        EC(Asn1Integer(3)),
        AES(Asn1Integer(32)),
        TRIPLE_DES(Asn1Integer(33)),
        HMAC(Asn1Integer(128));
        // From: https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/android/hardware/security/keymint/Algorithm.aidl

        companion object Tag : Tagged(2uL), Asn1Decodable<Asn1Primitive, Algorithm> {
            fun valueOf(int: Asn1Integer) = entries.first { it.intValue == int }
            override fun doDecode(src: Asn1Primitive) = valueOf(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    class KeySize private constructor(override val intValue: Asn1Integer) : IntEncodable {
        constructor(keyLength: BitLength) : this(Asn1Integer(keyLength.bits))

        companion object Tag : Tagged(3uL), Asn1Decodable<Asn1Primitive, KeySize> {
            override fun doDecode(src: Asn1Primitive) = KeySize(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
        override fun toString(): String {
            return "KeySize(intValue=$intValue)"
        }
    }

    enum class Digest(override val intValue: Asn1Integer) : IntEncodable {
        NONE(Asn1Integer(0)),
        MD5(Asn1Integer(1)),
        SHA1(Asn1Integer(2)),
        SHA_2_224(Asn1Integer(3)),
        SHA_2_256(Asn1Integer(4)),
        SHA_2_384(Asn1Integer(5)),
        SHA_2_512(Asn1Integer(6));
        // From: https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/android/hardware/security/keymint/Digest.aidl

        companion object Tag : Tagged(5uL), Asn1Decodable<Asn1Primitive, Digest> {
            fun valueOf(int: Asn1Integer) = entries.first { it.intValue == int }
            override fun doDecode(src: Asn1Primitive) = valueOf(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    enum class Padding(override val intValue: Asn1Integer) : IntEncodable {
        NONE(Asn1Integer(1)),
        RSA_OAEP(Asn1Integer(2)),
        RSA_PSS(Asn1Integer(3)),
        RSA_PKCS1_1_5_ENCRYPT(Asn1Integer(4)),
        RSA_PKCS1_1_5_SIGN(Asn1Integer(5)),
        PKCS7(Asn1Integer(64));
        // From: https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/android/hardware/security/keymint/PaddingMode.aidl

        companion object Tag : Tagged(6uL), Asn1Decodable<Asn1Primitive, Padding> {
            fun valueOf(int: Asn1Integer) = entries.first { it.intValue == int }
            override fun doDecode(src: Asn1Primitive) = valueOf(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }


    enum class ECCurve(override val intValue: Asn1Integer) : IntEncodable {
        P_224(Asn1Integer(0)),
        P_256(Asn1Integer(1)),
        P_384(Asn1Integer(2)),
        P_521(Asn1Integer(3)),
        CURVE_25519(Asn1Integer(4));
        // From: https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/android/hardware/security/keymint/EcCurve.aidl

        companion object Tag : Tagged(10uL), Asn1Decodable<Asn1Primitive, ECCurve> {
            fun valueOf(int: Asn1Integer) = entries.first { it.intValue == int }
            override fun doDecode(src: Asn1Primitive) = valueOf(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    class RsaPublicExponent private constructor(override val intValue: Asn1Integer) : IntEncodable {
        constructor(exponent: Asn1Integer.Positive) : this(intValue = exponent)

        companion object Tag : Tagged(200uL), Asn1Decodable<Asn1Primitive, RsaPublicExponent> {
            override fun doDecode(src: Asn1Primitive) = RsaPublicExponent(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
        override fun toString(): String {
            return "RsaPublicExponent($intValue)"
        }

    }

    // TODO set of integers
    //MGF digest is undocumented. tough luck my friend!
    class MgfDigest(override val intValue: Asn1Integer) : IntEncodable {
        companion object Tag : Tagged(203uL), Asn1Decodable<Asn1Primitive, MgfDigest> {
            override fun doDecode(src: Asn1Primitive) = MgfDigest(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    object RollbackResistance : Tagged(303uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    object EarlyBootOnly : Tagged(305uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    class ActiveDateTime private constructor(override val intValue: Asn1Integer) : IntEncodable {
        constructor(notBefore: Instant) : this(Asn1Integer(notBefore.toEpochMilliseconds()))

        companion object Tag : Tagged(400uL), Asn1Decodable<Asn1Primitive, ActiveDateTime> {
            override fun doDecode(src: Asn1Primitive) = ActiveDateTime(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    class OriginationExpireDateTime private constructor(override val intValue: Asn1Integer) :
        IntEncodable {
        constructor(notAfter: Instant) : this(Asn1Integer(notAfter.toEpochMilliseconds()))

        companion object Tag : Tagged(401uL),
            Asn1Decodable<Asn1Primitive, OriginationExpireDateTime> {
            override fun doDecode(src: Asn1Primitive) =
                OriginationExpireDateTime(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    class UsageExpireDateTime private constructor(override val intValue: Asn1Integer) :
        IntEncodable {
        constructor(notAfter: Instant) : this(Asn1Integer(notAfter.toEpochMilliseconds()))

        companion object Tag : Tagged(402uL), Asn1Decodable<Asn1Primitive, UsageCountLimit> {
            override fun doDecode(src: Asn1Primitive) = UsageCountLimit(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    class UsageCountLimit(override val intValue: Asn1Integer) : IntEncodable {
        companion object Tag : Tagged(405uL), Asn1Decodable<Asn1Primitive, UsageCountLimit> {
            override fun doDecode(src: Asn1Primitive) = UsageCountLimit(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    object NoAuthRequired : Tagged(503uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }


    /**
     * As per the [KeyMaster AIDL](https://android.googlesource.com/platform/hardware/interfaces/+/refs/heads/main/keymaster/aidl/android/hardware/keymaster/HardwareAuthenticatorType.aidl)
     * * `NONE` is modelled as empty set.
     * * `ANY` has a distinct representation as a set containing only the [Type.ANY] element
     */
    data class UserAuth(override val intValue: Asn1Integer) : IntEncodable {
        val authTypes: Set<Type> = when (intValue) {
            Type.ANY.intValue -> setOf(Type.ANY)
            Asn1Integer.ZERO -> emptySet()
            else -> {
                val raw = intValue.toBigInteger().longValue(exactRequired = false)
                val collected = mutableSetOf<Type>()
                if (raw and 1L > 0L) collected += Type.PASSWORD
                if (raw and 2L > 0L) collected += Type.FINGERPRINT
                collected
            }
        }

        companion object Tag : Tagged(504uL), Asn1Decodable<Asn1Primitive, UserAuth> {
            override fun doDecode(src: Asn1Primitive) = UserAuth(src.decodeToAsn1Integer())

            val NONE = UserAuth(Asn1Integer(0))
            val ANY = UserAuth(Asn1Integer(UInt.MAX_VALUE))
        }

        enum class Type(val intValue: Asn1Integer) {
            ANY(Asn1Integer(UInt.MAX_VALUE)),
            PASSWORD(Asn1Integer(1u)),
            FINGERPRINT(Asn1Integer(2u));
        }

        override val tagged get() = Tag
        override fun toString(): String {
            return "UserAuth(" +
                    "authTypes=$authTypes, " +
                    "intValue=$intValue" +
                    ")"
        }


    }

    class AuthTimeout private constructor(override val intValue: Asn1Integer) : IntEncodable {
        constructor(duration: Duration) : this(Asn1Integer(duration.inWholeSeconds))

        val duration: Duration =
            Long.decodeFromAsn1ContentBytes(intValue.encodeToAsn1ContentBytes()).seconds

        init {
            require(intValue.magnitude.size <= 4) // TODO: where is this specified?
        }

        companion object Tag : Tagged(505uL), Asn1Decodable<Asn1Primitive, AuthTimeout> {
            override fun doDecode(src: Asn1Primitive) = AuthTimeout(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
        override fun toString(): String {
            return "AuthTimeout(intValue=$intValue, duration=$duration)"
        }
    }

    object AllowWhileOnBody : Tagged(506uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    object TrustedUserPresenceRequired : Tagged(507uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    object TrustedConfirmationRequired : Tagged(508uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    object UnlockedDeviceRequired : Tagged(509uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    object AllApplications : Tagged(600uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    class CreationDateTime private constructor(override val intValue: Asn1Integer) : IntEncodable {
        constructor(timestamp: Instant) : this(Asn1Integer(timestamp.toEpochMilliseconds()))

        val timestamp: Instant =
            Instant.fromEpochMilliseconds(Long.decodeFromAsn1ContentBytes(intValue.encodeToAsn1ContentBytes()))

        companion object Tag : Tagged(701uL), Asn1Decodable<Asn1Primitive, CreationDateTime> {
            override fun doDecode(src: Asn1Primitive) = CreationDateTime(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
        override fun toString(): String {
            return "CreationDateTime(intValue=$intValue, timestamp=$timestamp)"
        }
    }

    enum class Origin(override val intValue: Asn1Integer) : IntEncodable {
        GENERATED(Asn1Integer(0)),
        DERIVED(Asn1Integer(1)),
        IMPORTED(Asn1Integer(2)),
        RESERVED(Asn1Integer(3)),
        SECURELY_IMPORTED(Asn1Integer(4));
        // From: https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/android/hardware/security/keymint/KeyOrigin.aidl

        companion object Tag : Tagged(702uL), Asn1Decodable<Asn1Primitive, Origin> {
            fun valueOf(int: Asn1Integer) = entries.first { it.intValue == int }
            override fun doDecode(src: Asn1Primitive) = valueOf(src.decodeToAsn1Integer())
        }

        override val tagged get() = Tag
    }

    object RollbackResistent : Tagged(703uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }

    class RootOfTrust private constructor(
        val verifiedBootKeyDigest: ByteArray,
        val deviceLocked: Boolean,
        val verifiedBootState: VerifiedBootState,
        val verifiedBootHash: ByteArray?,
        val actualBooleanValue: ByteArray
    ) : Asn1Encodable<Asn1Sequence>, Tagged.WithTag<Asn1Sequence>, PrettyPrintable {

        constructor(
            verifiedBootKeyDigest: ByteArray,
            deviceLocked: Boolean,
            verifiedBootState: VerifiedBootState,
            verifiedBootHash: ByteArray?
        ) : this(
            verifiedBootKeyDigest = verifiedBootKeyDigest,
            deviceLocked = deviceLocked,
            verifiedBootState = verifiedBootState,
            verifiedBootHash = verifiedBootHash,
            actualBooleanValue = Asn1.Bool(deviceLocked).content
        )

        companion object Tag : Tagged(704uL), Asn1Decodable<Asn1Sequence, RootOfTrust> {
            override fun doDecode(src: Asn1Sequence) = src.iterator().run {
                //NON-DER encoding. Why are the biggest players most incompetent?
                val verifiedBootKeyDigest = next().asPrimitive().content
                val (deviceLocked, actualBooleanValue) = next().asPrimitive().decode(Asn1Element.Tag.BOOL) {
                    //This isn't even DER-compliant!
                    (it.firstOrNull { it != 0.toByte() } != null) to it
                }
                val verifiedBootState = VerifiedBootState.decodeFromTlv(next().asPrimitive())
                val verifiedBootHash = if (hasNext()) next().asPrimitive().content else null

                RootOfTrust(
                    verifiedBootKeyDigest,
                    deviceLocked,
                    verifiedBootState,
                    verifiedBootHash,
                    actualBooleanValue
                )
            }
        }

        override val tagged get() = Tag

        override fun encodeToTlv() = Asn1.Sequence {
            +Asn1.OctetString(verifiedBootKeyDigest)
            +Asn1Primitive(Asn1Element.Tag.BOOL, actualBooleanValue)
            +verifiedBootState
            verifiedBootHash?.let { +Asn1.OctetString(it) }
        }

        @OptIn(ExperimentalStdlibApi::class)
        override fun toString(): String {
            return "RootOfTrust(verifiedBootKeyDigest=${verifiedBootKeyDigest.toHexString()}, deviceLocked=$deviceLocked, verifiedBootState=$verifiedBootState, verifiedBootHash=${verifiedBootHash?.toHexString()})"
        }

        @OptIn(ExperimentalStdlibApi::class)
        override fun doPrettyPrint(indent: String): String = buildString {
            val i = indent + "  "
            append(indent).append("RootOfTrust(\n")
            append(i).append("verifiedBootKeyDigest=").append(verifiedBootKeyDigest.toHexString()).append('\n')
            append(i).append("deviceLocked=").append(deviceLocked).append('\n')
            append(i).append("verifiedBootState=").append(verifiedBootState).append('\n')
            append(i).append("verifiedBootHash=").append(verifiedBootHash?.toHexString()).append('\n')
            append(indent).append(")")
        }


        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is RootOfTrust) return false

            if (deviceLocked != other.deviceLocked) return false
            if (!verifiedBootKeyDigest.contentEquals(other.verifiedBootKeyDigest)) return false
            if (verifiedBootState != other.verifiedBootState) return false
            if (!verifiedBootHash.contentEquals(other.verifiedBootHash)) return false

            return true
        }

        override fun hashCode(): Int {
            var result = deviceLocked.hashCode()
            result = 31 * result + verifiedBootKeyDigest.contentHashCode()
            result = 31 * result + verifiedBootState.hashCode()
            result = 31 * result + verifiedBootHash.contentHashCode()
            return result
        }

        enum class VerifiedBootState(val intValue: UInt) : Asn1Encodable<Asn1Primitive> {
            Verified(0u),
            SelfSigned(1u),
            Unverified(2u),
            Failed(3u);
            // From: https://source.android.com/docs/security/features/keystore/attestation#schema

            override fun encodeToTlv() =
                Asn1Primitive(BERTags.ENUMERATED, intValue.encodeToAsn1ContentBytes())

            companion object : Asn1Decodable<Asn1Primitive, VerifiedBootState> {
                fun valueOf(int: UInt) = entries.first { it.intValue == int }
                override fun doDecode(src: Asn1Primitive) = src.decodeToEnum<VerifiedBootState>()
            }
        }
    }

    class OsVersion(
        val major: UByte,
        val minor: UByte,
        val sub: UByte
    ) : IntEncodable {
        override val intValue =
            Asn1Integer(sub.toUInt() + minor.toUInt() * 100u + major.toUInt() * 10000u)

        companion object Tag : Tagged(705uL), Asn1Decodable<Asn1Primitive, OsVersion> {
            override fun doDecode(src: Asn1Primitive): OsVersion {
                val raw = Long.decodeFromAsn1ContentBytes(
                    src.decodeToAsn1Integer().encodeToAsn1ContentBytes()
                )
                val sub = raw % 100
                val minor = (raw % 10000) / 100
                val major = raw / 10000
                return OsVersion(major.toUByte(), minor.toUByte(), sub.toUByte())
            }
        }

        override val tagged get() = Tag
        override fun toString(): String {
            return "OsVersion(major=$major, minor=$minor, sub=$sub, intValue=$intValue)"
        }
    }

    class OsPatchLevel(
        val year: UShort,
        val month: Month
    ) : IntEncodable {

        override val intValue = Asn1Integer(month.number.toUInt() + year.toUInt() * 100u)

        companion object Tag : Tagged(706uL), Asn1Decodable<Asn1Primitive, OsPatchLevel> {
            override fun doDecode(src: Asn1Primitive): OsPatchLevel {
                val raw = Long.decodeFromAsn1ContentBytes(
                    src.decodeToAsn1Integer().encodeToAsn1ContentBytes()
                )
                val year = raw / 100
                val month = Month((raw % 100).toInt())
                return OsPatchLevel(year.toUShort(), month)
            }
        }

        override val tagged get() = Tag
        override fun toString(): String {
            return "OsPatchLevel(year=$year, month=$month, intValue=$intValue)"
        }
    }

    /**
     * TODO: encodeSorted beschreiben und erklären warum listen und nicht sets
     * eventuell auch für andrere SETs wie digets padding...
     */
    class AttestationApplicationId internal constructor(
        val packageInfos: List<AttestationPackageInfo>,
        val signatureDigests: List<ByteArray>,
        private val encodeSorted: Boolean
    ) : Asn1Encodable<Asn1Element>, Tagged.WithTag<Asn1Element>, PrettyPrintable {
        companion object Tag : Tagged(709uL), Asn1Decodable<Asn1Element, AttestationApplicationId> {
            override fun doDecode(src: Asn1Element): AttestationApplicationId {
                val children = src.asEncapsulatingOctetString().children
                require(children.size == 1) // TODO: check others TLV entries so that at most 1 is given
                val sequence = children.first().asSequence()

                return sequence.iterator().run {
                    AttestationApplicationId(
                        next().asSet().children.map { AttestationPackageInfo.decodeFromTlv(it.asSequence()) },
                        next().asSet().children.map { it.asOctetString().content },
                        encodeSorted = false
                    )
                }
            }
        }

        constructor(packageInfos: Set<AttestationPackageInfo>, signatureDigests: Set<ByteArray>)
                : this(packageInfos.toList(), signatureDigests.toList(), encodeSorted = true)

        override val tagged get() = Tag

        override fun encodeToTlv(): Asn1Element = Asn1.OctetStringEncapsulating {
            +Asn1.Sequence {
                if (encodeSorted) {
                    +Asn1.SetOf { packageInfos.forEach { +it } }
                    +Asn1.SetOf { signatureDigests.forEach { +Asn1.OctetString(it) } }
                } else {
                    +Asn1Set.fromPresorted(packageInfos.map { it.encodeToTlv() })
                    +Asn1Set.fromPresorted(signatureDigests.map { it.encodeToAsn1OctetStringPrimitive() })
                }
            }
        }

        @OptIn(ExperimentalStdlibApi::class)
        override fun toString(): String {
            return "AttestationApplicationId(packageInfos=${packageInfos}, signatureDigests=${signatureDigests.map { it.toHexString() }})"
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other == null || this::class != other::class) return false

            other as AttestationApplicationId

            if (encodeSorted != other.encodeSorted) return false
            if (packageInfos != other.packageInfos) return false
            if (signatureDigests != other.signatureDigests) return false

            return true
        }

        override fun hashCode(): Int {
            var result = encodeSorted.hashCode()
            result = 31 * result + packageInfos.hashCode()
            result = 31 * result + signatureDigests.hashCode()
            return result
        }

        // AuthorizationList.AttestationApplicationId.prettyPrint
        @OptIn(ExperimentalStdlibApi::class)
        override fun doPrettyPrint(indent: String): String = buildString {
            val i = indent + "  "
            append(indent).append("AttestationApplicationId(\n")

            append(i).append("packageInfos = [\n")
            packageInfos.forEach { pi ->
                append(i).append("  ").append(pi).append('\n')
            }
            append(i).append("]\n")

            append(i).append("signatureDigests = [\n")
            signatureDigests.forEach { d ->
                append(i).append("  ").append(d.toHexString()).append('\n')
            }
            append(i).append("]\n")

            append(indent).append(")")
        }


        enum class VerifiedBootState(val intValue: UInt) : Asn1Encodable<Asn1Primitive> {
            Verified(0u),
            SelfSigned(1u),
            Unverified(2u),
            Failed(3u);
            // From: https://source.android.com/docs/security/features/keystore/attestation#schema

            override fun encodeToTlv() =
                Asn1Primitive(BERTags.ENUMERATED, intValue.encodeToAsn1ContentBytes())

            companion object : Asn1Decodable<Asn1Primitive, VerifiedBootState> {
                fun valueOf(int: UInt) = entries.first { it.intValue == int }
                override fun doDecode(src: Asn1Primitive) = src.decodeToEnum<VerifiedBootState>()
            }
        }
    }

    data class AttestationPackageInfo(
        val packageName: String,
        val version: UInt
    ) : Asn1Encodable<Asn1Sequence> {
        companion object :
            Asn1Decodable<Asn1Sequence, AttestationPackageInfo> {
            override fun doDecode(src: Asn1Sequence) = src.iterator().run {
                AttestationPackageInfo(
                    next().asOctetString().content.decodeToString(),
                    next().asPrimitive().decodeToUInt()
                )
            }
        }

        override fun encodeToTlv() = Asn1.Sequence {
            +Asn1.OctetString(packageName.encodeToByteArray())
            +Asn1.Int(version)
        }

        override fun toString(): String {
            return "AttestationPackageInfo(packageName='$packageName', version=$version)"
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AttestationPackageInfo) return false

            if (packageName != other.packageName) return false
            if (version != other.version) return false

            return true
        }

        override fun hashCode(): Int {
            var result = packageName.hashCode()
            result = 31 * result + version.hashCode()
            return result
        }
    }

    sealed class AttestationId(val stringValue: String) : Asn1Encodable<Asn1Primitive>,
        Tagged.WithTag<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.OctetString(stringValue.encodeToByteArray())
        override fun toString(): String {
            return "AttestationId(stringValue='$stringValue')"
        }

        class Brand(name: String) : AttestationId(name) {
            companion object Tag : Tagged(710uL)

            override val tagged get() = Tag
        }

        class Device(name: String) : AttestationId(name) {
            companion object Tag : Tagged(711uL), Asn1Decodable<Asn1Primitive, Device> {
                override fun doDecode(src: Asn1Primitive) =
                    Device(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }

        class Product(name: String) : AttestationId(name) {
            companion object Tag : Tagged(712uL), Asn1Decodable<Asn1Primitive, Product> {
                override fun doDecode(src: Asn1Primitive) =
                    Product(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }

        class Serial(number: String) : AttestationId(number) {
            companion object Tag : Tagged(713uL), Asn1Decodable<Asn1Primitive, Serial> {
                override fun doDecode(src: Asn1Primitive) =
                    Serial(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }

        class Imei(number: String) : AttestationId(number) {
            companion object Tag : Tagged(714uL), Asn1Decodable<Asn1Primitive, Imei> {
                override fun doDecode(src: Asn1Primitive) =
                    Imei(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }

        class Meid(number: String) : AttestationId(number) {
            companion object Tag : Tagged(715uL), Asn1Decodable<Asn1Primitive, Meid> {
                override fun doDecode(src: Asn1Primitive) =
                    Meid(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }

        class Manufacturer(name: String) : AttestationId(name) {
            companion object Tag : Tagged(716uL), Asn1Decodable<Asn1Primitive, Manufacturer> {
                override fun doDecode(src: Asn1Primitive) =
                    Manufacturer(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }

        class Model(name: String) : AttestationId(name) {
            companion object Tag : Tagged(717uL), Asn1Decodable<Asn1Primitive, Model> {
                override fun doDecode(src: Asn1Primitive) =
                    Model(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }

        class SecondImei(number: String) : AttestationId(number) {
            companion object Tag : Tagged(723uL), Asn1Decodable<Asn1Primitive, SecondImei> {
                override fun doDecode(src: Asn1Primitive) =
                    SecondImei(src.asOctetString().content.decodeToString())
            }

            override val tagged get() = Tag
        }
    }

    sealed class PatchLevel(
        val year: UShort,
        val month: Month,
        val day: UShort? /*This is non-compliant, but many OEMs mess this up AND the legacy google parser is also lenient here*/
    ) : IntEncodable {
        override val intValue =
            if (day == null)
                Asn1Integer(month.number.toUInt() + year.toUInt() * 100u)
            else
                Asn1Integer(day.toUInt() + month.number.toUInt() * 100u + year.toUInt() * 10000u)

        companion object {
            fun Asn1Primitive.decode(): Triple<UShort, Month, UShort?> {
                val raw = Long.decodeFromAsn1ContentBytes(
                    decodeToAsn1Integer().encodeToAsn1ContentBytes()
                )
                if (raw > 999999) {
                    val day = raw % 100
                    val monthNumber = (raw % 10000) / 100
                    val year = raw / 10000
                    return Triple(
                        year.toUShort(),
                        Month(monthNumber.toInt()),
                        day.toUShort()
                    )
                } else {
                    val monthNumber = (raw % 100)
                    val year = raw / 100
                    return Triple(
                        year.toUShort(),
                        Month(monthNumber.toInt()),
                        null
                    )
                }
            }
        }

        class Vendor(
            year: UShort,
            month: Month,
            day: UShort?
        ) : PatchLevel(year, month, day) {
            companion object Tag : Tagged(718uL), Asn1Decodable<Asn1Primitive, Vendor> {
                override fun doDecode(src: Asn1Primitive): Vendor = src.decode().let { (y, m, d) ->
                    Vendor(y, m, d)
                }

            }

            override val tagged get() = Tag
        }

        class Boot(
            year: UShort,
            month: Month,
            day: UShort?
        ) : PatchLevel(year, month, day) {
            companion object Tag : Tagged(719uL), Asn1Decodable<Asn1Primitive, Boot> {
                override fun doDecode(src: Asn1Primitive): Boot = src.decode().let { (y, m, d) ->
                    Boot(y, m, d)
                }
            }

            override val tagged get() = Tag
        }

        override fun toString(): String {
            return "PatchLevel(year=$year, month=$month, day=$day, intValue=$intValue)"
        }
    }

    /**
     * Can only ever be set by privileged system apps
     */
    object DeviceUniqueAttestation : Tagged(720uL), Asn1Encodable<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.Null()
    }


    /**
     * #### Undocumented, ChatGPT-generated! Take with a grain of salt!
     * In the context of Android's Keymaster and Keystore systems, the `moduleHash` is a component within the attestation data structure, specifically in the `KeyDescription` sequence. It provides a cryptographic representation of the software environment associated with the key's creation and usage.
     *
     * **Computation of `moduleHash`:**
     *
     * 1. **Modules Collection:**
     *    - The system gathers a set of `Module` entries, each representing an APEX (Android Pony EXpress) module.
     *    - Each `Module` includes:
     *      - **Package Name (`packageName`):** An octet string identifying the module.
     *      - **Version (`version`):** An integer indicating the module's version at boot time.
     *
     * 2. **DER Encoding:**
     *    - The `Modules` set is encoded using Distinguished Encoding Rules (DER), a binary encoding format for data structures described by ASN.1.
     *    - DER encoding ensures a unique, unambiguous representation of the data, which is crucial for consistent hashing.
     *
     * 3. **Ordering:**
     *    - Within the DER encoding process, the `Module` entries are ordered lexicographically by their encoded value.
     *    - This deterministic ordering guarantees that the same set of modules will always produce the same encoded output, ensuring consistency in the hash computation.
     *
     * 4. **SHA-256 Hashing:**
     *    - The system computes the SHA-256 hash of the DER-encoded `Modules` set.
     *    - The resulting 256-bit hash value is the `moduleHash`.
     *
     * This `moduleHash` serves as a fingerprint of the software environment, allowing verification processes to detect any unauthorized changes to the modules. By including the `moduleHash` in the attestation data, the system provides assurance that the key is used within a trusted and unaltered software environment.
     *
     * For a detailed definition of the `Modules` and `Module` structures, as well as the computation of `moduleHash`, you can refer to the Android Open Source Project's documentation on Keymaster's attestation process.
     */
    class ModuleHash(val sha256Digest: ByteArray) : Asn1Encodable<Asn1Primitive>,
        Tagged.WithTag<Asn1Primitive> {
        override fun encodeToTlv() = Asn1.OctetString(sha256Digest)

        @OptIn(ExperimentalStdlibApi::class)
        override fun toString(): String {
            return "ModuleHash(sha256Digest=${sha256Digest.toHexString()})"
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is ModuleHash) return false

            if (!sha256Digest.contentEquals(other.sha256Digest)) return false

            return true
        }

        override fun hashCode(): Int {
            return sha256Digest.contentHashCode()
        }

        companion object Tag : Tagged(724uL), Asn1Decodable<Asn1Primitive, ModuleHash> {
            override fun doDecode(src: Asn1Primitive) = ModuleHash(src.asOctetString().content)
        }

        override val tagged get() = Tag
    }
}

private class TrackingSequence(val src: Asn1Structure) {
    val readTags: List<Asn1Element.Tag> = mutableListOf()
    fun markExtracted(tag: Asn1Element.Tag) {
        (readTags as MutableList<Asn1Element.Tag>) += tag
    }
    fun retainUnread() = src.children.toMutableList().apply { removeAll { readTags.contains(it.tag) }}
}
