package at.asitplus.attestation.android

import com.zkdcloud.proxy.http.ServerStart
import com.zkdcloud.proxy.http.handler.client.ExceptionDuplexHandler
import com.zkdcloud.proxy.http.handler.client.JudgeTypeInboundHandler
import at.asitplus.testballoon.matrix.*
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.matchers.booleans.shouldBeFalse
import io.kotest.matchers.booleans.shouldBeTrue
import io.kotest.matchers.comparables.shouldBeGreaterThan
import io.kotest.matchers.shouldBe
import io.ktor.client.engine.mock.*
import io.ktor.client.request.*
import io.ktor.http.*
import io.ktor.util.date.*
import io.ktor.utils.io.*
import io.netty.bootstrap.ServerBootstrap
import io.netty.buffer.PooledByteBufAllocator
import io.netty.channel.Channel
import io.netty.channel.ChannelFuture
import io.netty.channel.ChannelInitializer
import io.netty.channel.ChannelOption
import io.netty.channel.nio.NioEventLoopGroup
import io.netty.channel.socket.nio.NioServerSocketChannel
import io.netty.handler.codec.http.HttpRequestDecoder
import io.netty.handler.codec.http.HttpResponseEncoder
import io.netty.handler.timeout.IdleStateHandler
import io.netty.util.concurrent.DefaultThreadFactory
import org.slf4j.LoggerFactory
import java.io.ByteArrayInputStream
import java.io.File
import java.math.BigInteger
import java.net.ConnectException
import java.nio.charset.StandardCharsets
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate
import java.time.ZoneOffset
import java.util.concurrent.TimeUnit
import kotlin.math.min
import kotlin.time.Clock
import kotlin.time.Duration.Companion.hours
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Duration.Companion.seconds
import kotlin.time.ExperimentalTime
import kotlin.time.Instant
import kotlin.time.toKotlinInstant


const val TEST_STATUS_LIST_PATH = "../../dependencies/android-key-attestation/src/test/resources/status.json"

// Certificate generated by TestDPC with RSA Algorithm and StrongBox Security Level
val TEST_CERT = """
        -----BEGIN CERTIFICATE-----
        MIIB8zCCAXqgAwIBAgIRAMxm6ak3E7bmQ7JsFYeXhvcwCgYIKoZIzj0EAwIwOTEMMAoGA1UEDAwDVEVFMSkwJwYDVQQFEyA0ZjdlYzg1N2U4MDU3
        NDdjMWIxZWRhYWVmODk1NDk2ZDAeFw0xOTA4MTQxOTU0MTBaFw0yOTA4MTExOTU0MTBaMDkxDDAKBgNVBAwMA1RFRTEpMCcGA1UEBRMgMzJmYmJi
        NmRiOGM5MTdmMDdhYzlhYjZhZTQ4MTAzYWEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQzg+sx9lLrkNIZwLYZerzL1bPK2zi75zFEuuI0fIr3
        5DJND1B4Z8RPZ3djzo3FOdAObqvoZ4CZVxcY3iQ1ffMMo2MwYTAdBgNVHQ4EFgQUzZOUqhJOO7wttSe9hYemjceVsgIwHwYDVR0jBBgwFoAUWlnI
        9iPzasns60heYXIP+h+Hz8owDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAgQwCgYIKoZIzj0EAwIDZwAwZAIwUFz/AKheCOPaBiRGDk7L
        aSEDXVYmTr0VoU8TbIqrKGWiiMwsGEmW+Jdo8EcKVPIwAjAoO7n1ruFh+6mEaTAukc6T5BW4MnmYadkkFSIjzDAaJ6lAq+nmmGQ1KlZpqi4Z/VI=
        -----END CERTIFICATE-----
        """.trimIndent()


@OptIn(ExperimentalTime::class)
val RevocationTests by matrixSuite {

    "custom implementation" - {

        val factory = CertificateFactory.getInstance("X509")
        val cert =
            factory.generateCertificate(ByteArrayInputStream(TEST_CERT.toByteArray(StandardCharsets.UTF_8))) as X509Certificate
        val serialNumber = cert.serialNumber

        "File-based" {

            val load =
                AndroidRevocationList.FileLoader(TEST_STATUS_LIST_PATH, 0L).load(Clock.System.now())
            load
                .isRevokedOrSuspended(serialNumber).shouldBeTrue()

            load.isRevokedOrSuspended(BigInteger.valueOf(0xbadbeef)).shouldBeFalse()
        }

        "Date-only expires parsing" {
            val list = AndroidRevocationList.deserialize(
                """{"entries":{"abcd":{"status":"SUSPENDED","expires":"2025-01-31"}}}"""
            )
            val expected = java.time.LocalDate.parse("2025-01-31")
                .atStartOfDay(ZoneOffset.UTC)
                .toInstant()
                .toKotlinInstant()
            list.entries["abcd"]!!.expires shouldBe expected
        }

        "test cache" - {

            "without HTTP Expiry Header" {
                val now = Clock.System.now()
                val client = AndroidRevocationList.HttpLoader(
                    MockEngine,
                    url = "",
                    fallbackRevocationListValiditySeconds = 0L
                ) {
                    engine { requestHandlers.add(setResponse(now, withExpiry1Hour = false)) }
                }
                val first = client.load(now)
                first.expires shouldBe now
                val times = 1000
                repeat(times) {
                    var newList = client.load(now)
                    newList.expires shouldBe now
                    (newList === first).shouldBeFalse()
                }
            }

            "with HTTP Expiry Header" {
                val now = Instant.fromEpochSeconds(Clock.System.now().epochSeconds)
                val client = AndroidRevocationList.HttpLoader(
                    MockEngine,
                    url = "",
                    fallbackRevocationListValiditySeconds = 0L
                ) {
                    engine { requestHandlers.add(setResponse(now, withExpiry1Hour = true)) }
                }

                val first = client.load(now)
                val times = 1000
                repeat(times) {
                    (client.load(now) === first).shouldBeTrue()
                    first.expires shouldBe now + 1.hours
                }
            }

            "with Cache-Control max-age" {
                val now = Clock.System.now()
                val client = AndroidRevocationList.HttpLoader(
                    MockEngine,
                    url = "",
                    fallbackRevocationListValiditySeconds = 0L
                ) {
                    engine {
                        requestHandlers.add {
                            val headers = headers {
                                append(HttpHeaders.CacheControl, "public, max-age=3600, Wumbo")
                                append(HttpHeaders.ContentType, "application/json")
                            }
                            respond(
                                content = ByteReadChannel(File(TEST_STATUS_LIST_PATH).readBytes()),
                                status = HttpStatusCode.OK,
                                headers = headers
                            )
                        }
                    }
                }

                val first = client.load(now)
                first.expires shouldBe now + 1.hours
            }

            "refresh after expiry returns fresh instance" {
                val now = Instant.fromEpochSeconds(Clock.System.now().epochSeconds)
                var fetches = 0
                val client = AndroidRevocationList.HttpLoader(
                    MockEngine,
                    url = "",
                    fallbackRevocationListValiditySeconds = 0L,
                    preferHeaderBasedExpiry = true,
                ) {
                    engine {
                        requestHandlers.add {
                            fetches++
                            respond(
                                content = ByteReadChannel("""{"entries":{}}""".toByteArray(StandardCharsets.UTF_8)),
                                status = HttpStatusCode.OK,
                                headers = headers {
                                    append(HttpHeaders.CacheControl, "max-age=2")
                                    append(HttpHeaders.ContentType, "application/json")
                                }
                            )
                        }
                    }
                }

                val first = client.load(now)
                repeat(1000){(client.load(now) === first).shouldBeTrue() }
                val second = client.load(now + 1.seconds)
                repeat(1000){(client.load(now) === second).shouldBeTrue() }
                val third = client.load(now + 3.seconds)
                repeat(1000){(client.load(now) === third).shouldBeTrue() }

                (second === first).shouldBeTrue()
                (third === first).shouldBeFalse()
                fetches shouldBe 2
            }

            "expiry precedence (json vs headers vs fallback)" - {
                data class Scenario(
                    val jsonExpiresInSeconds: Long?,
                    val cacheControlHeader: String?,
                    val expiresHeaderSeconds: Long?,
                    val expiresHeaderRaw: String?,
                    val fallbackSeconds: Long,
                    val expectedPreferHeadersSeconds: Long,
                    val expectedPreferJsonSeconds: Long,
                )

                val scenarios = linkedMapOf(
                    "prefer headers even if json shorter" to Scenario(
                        jsonExpiresInSeconds = (30.minutes).inWholeSeconds,
                        cacheControlHeader = "public, max-age=3600",
                        expiresHeaderSeconds = null,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 9999,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = (30.minutes).inWholeSeconds,
                    ),
                    "no-cache forces immediate expiry" to Scenario(
                        jsonExpiresInSeconds = 5.hours.inWholeSeconds,
                        cacheControlHeader = "no-cache, max-age=3600",
                        expiresHeaderSeconds = 1.hours.inWholeSeconds,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 9999,
                        expectedPreferHeadersSeconds = 0,
                        expectedPreferJsonSeconds = 5.hours.inWholeSeconds,
                    ),
                    "cache-control wins over expires" to Scenario(
                        jsonExpiresInSeconds = 5.hours.inWholeSeconds,
                        cacheControlHeader = "public, max-age=3600, Wumbo",
                        expiresHeaderSeconds = (90.minutes).inWholeSeconds,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 9999,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = 5.hours.inWholeSeconds,
                    ),
                    "cache-control wins even if longer" to Scenario(
                        jsonExpiresInSeconds = 5.hours.inWholeSeconds,
                        cacheControlHeader = "public, max-age=5400",
                        expiresHeaderSeconds = 1.hours.inWholeSeconds,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 9999,
                        expectedPreferHeadersSeconds = (90.minutes).inWholeSeconds,
                        expectedPreferJsonSeconds = 5.hours.inWholeSeconds,
                    ),
                    "cache-control malformed -> expires" to Scenario(
                        jsonExpiresInSeconds = 5.hours.inWholeSeconds,
                        cacheControlHeader = "public, max-age=abc",
                        expiresHeaderSeconds = 1.hours.inWholeSeconds,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 9999,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = 5.hours.inWholeSeconds,
                    ),
                    "expires malformed -> cache-control" to Scenario(
                        jsonExpiresInSeconds = 5.hours.inWholeSeconds,
                        cacheControlHeader = "max-age=3600",
                        expiresHeaderSeconds = null,
                        expiresHeaderRaw = "not-a-date",
                        fallbackSeconds = 77,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = 5.hours.inWholeSeconds,
                    ),
                    "both headers malformed -> json" to Scenario(
                        jsonExpiresInSeconds = 1.hours.inWholeSeconds,
                        cacheControlHeader = "max-age=nope",
                        expiresHeaderSeconds = null,
                        expiresHeaderRaw = "not-a-date",
                        fallbackSeconds = 60,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = 1.hours.inWholeSeconds,
                    ),
                    "json absent -> min(headers)" to Scenario(
                        jsonExpiresInSeconds = null,
                        cacheControlHeader = "max-age=5400",
                        expiresHeaderSeconds = 1.hours.inWholeSeconds,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 77,
                        expectedPreferHeadersSeconds = (90.minutes).inWholeSeconds,
                        expectedPreferJsonSeconds = (90.minutes).inWholeSeconds,
                    ),
                    "json absent + expires malformed -> cache-control" to Scenario(
                        jsonExpiresInSeconds = null,
                        cacheControlHeader = "max-age=3600",
                        expiresHeaderSeconds = null,
                        expiresHeaderRaw = "not-a-date",
                        fallbackSeconds = 77,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = 1.hours.inWholeSeconds,
                    ),
                    "json absent + cache-control malformed -> expires" to Scenario(
                        jsonExpiresInSeconds = null,
                        cacheControlHeader = "max-age=abc",
                        expiresHeaderSeconds = 1.hours.inWholeSeconds,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 77,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = 1.hours.inWholeSeconds,
                    ),
                    "json absent + both headers malformed -> fallback" to Scenario(
                        jsonExpiresInSeconds = null,
                        cacheControlHeader = "max-age=abc",
                        expiresHeaderSeconds = null,
                        expiresHeaderRaw = "not-a-date",
                        fallbackSeconds = 77,
                        expectedPreferHeadersSeconds = 77,
                        expectedPreferJsonSeconds = 77,
                    ),
                    "json only (fallback must not override)" to Scenario(
                        jsonExpiresInSeconds = 1.hours.inWholeSeconds,
                        cacheControlHeader = null,
                        expiresHeaderSeconds = null,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 60,
                        expectedPreferHeadersSeconds = 1.hours.inWholeSeconds,
                        expectedPreferJsonSeconds = 1.hours.inWholeSeconds,
                    ),
                    "no expiry anywhere uses fallback" to Scenario(
                        jsonExpiresInSeconds = null,
                        cacheControlHeader = null,
                        expiresHeaderSeconds = null,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 123,
                        expectedPreferHeadersSeconds = 123,
                        expectedPreferJsonSeconds = 123,
                    ),
                    "multiple max-age picks shortest" to Scenario(
                        jsonExpiresInSeconds = null,
                        cacheControlHeader = "public, max-age=3600, max-age=10",
                        expiresHeaderSeconds = 1.hours.inWholeSeconds,
                        expiresHeaderRaw = null,
                        fallbackSeconds = 123,
                        expectedPreferHeadersSeconds = 10,
                        expectedPreferJsonSeconds = 10,
                    ),
                )

                data(
                    "header preference",
                    mapOf(
                        "parse expiry from headers" to true,
                        "ignore headers (JSON only)" to false,
                    ).values
                ) - { preferHeaderBasedExpiry ->
                    data("scenarios", scenarios.values) test { scenario ->
                        val now = Instant.fromEpochSeconds(Clock.System.now().epochSeconds)

                        val jsonExpires =
                            scenario.jsonExpiresInSeconds?.let { now + it.seconds }
                        val body = if (jsonExpires == null) {
                            """{"entries":{}}"""
                        } else {
                            """{"entries":{},"expires":"$jsonExpires"}"""
                        }

                        val expiresHeaderValue = scenario.expiresHeaderSeconds?.let {
                            GMTDate(now.toEpochMilliseconds() + it * 1000).toHttpDate()
                        } ?: scenario.expiresHeaderRaw

                        val client = AndroidRevocationList.HttpLoader(
                            MockEngine,
                            url = "",
                            fallbackRevocationListValiditySeconds = scenario.fallbackSeconds,
                            preferHeaderBasedExpiry = preferHeaderBasedExpiry
                        ) {
                            engine {
                                requestHandlers.add(
                                    setJsonResponse(
                                        now = now,
                                        body = body,
                                        expiresHeaderValue = expiresHeaderValue,
                                        cacheControlHeaderValue = scenario.cacheControlHeader
                                    )
                                )
                            }
                        }

                        val expectedSeconds = if (preferHeaderBasedExpiry) {
                            scenario.expectedPreferHeadersSeconds
                        } else {
                            scenario.expectedPreferJsonSeconds
                        }

                        val list = client.load(now)
                        list.expires shouldBe (now + expectedSeconds.seconds)
                    }
                }

                "invalid json expiry must throw" - {
                    data(
                        "header preference",
                        mapOf(
                            "parse expiry from headers" to true,
                            "ignore headers (JSON only)" to false,
                        ).values
                    ) - { preferHeaderBasedExpiry ->
                        "throws" {
                            val now = Instant.fromEpochSeconds(Clock.System.now().epochSeconds)
                            val client = AndroidRevocationList.HttpLoader(
                                MockEngine,
                                url = "",
                                fallbackRevocationListValiditySeconds = 999,
                                preferHeaderBasedExpiry = preferHeaderBasedExpiry
                            ) {
                                engine {
                                    requestHandlers.add(
                                        setJsonResponse(
                                            now = now,
                                            body = """{"entries":{},"expires":"not-an-instant"}""",
                                            expiresHeaderValue = GMTDate(now.toEpochMilliseconds() + 3600_000).toHttpDate(),
                                            cacheControlHeaderValue = "max-age=3600"
                                        )
                                    )
                                }
                            }
                            shouldThrow<Throwable> { client.load(now) }
                        }
                    }
                }
            }
        }

        "Test HTTP local proxy" {
            val client = AndroidRevocationList.HttpLoader.GoogleOfficial(
                fallbackRevocationListValiditySeconds = 0
            ).withHttpProxy("http://localhost:1081")
                .createLoader()
            shouldThrow<ConnectException> {
                client.load(Clock.System.now())
            }
            startProxy()
            val now = Clock.System.now()
            val revocationList = client.load(now)
            revocationList.isRevokedOrSuspended("6681152659205225093") shouldBe true
            revocationList.expires!! shouldBeGreaterThan now
            repeat(100000) {
                (client.load(Clock.System.now()) === revocationList).shouldBeTrue()

            }
        }
    }
}


//Ripped from MIT-Licences HTTP Proxy included as submodule. NOT PART OF RELEASE! Only Used for Testing
private fun startProxy(): ChannelFuture? {

    ServerStart.serverConfigure.port = 1081
    val serverBootstrap = ServerBootstrap()
    val logger = LoggerFactory.getLogger(ServerStart::class.java)

    val bossGroup = NioEventLoopGroup(
        min((Runtime.getRuntime().availableProcessors() + 1).toDouble(), 32.0)
            .toInt(), DefaultThreadFactory("boss-threads")
    )
    val workGroup = NioEventLoopGroup(
        ServerStart.serverConfigure.threadNumber,
        DefaultThreadFactory("workers-threads")
    )

    serverBootstrap.group(bossGroup, workGroup)
        .channel(NioServerSocketChannel::class.java)
        .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
        .childOption(ChannelOption.TCP_NODELAY, true)
        .childHandler(object : ChannelInitializer<Channel>() {
            @Throws(Exception::class)
            override fun initChannel(ch: Channel) {
                ch.pipeline()
                    .addLast("idle", IdleStateHandler(0, 0, ServerStart.serverConfigure.idleTime, TimeUnit.SECONDS))
                    .addLast("http-decoder", HttpRequestDecoder())
                    .addLast("http-encoder", HttpResponseEncoder())
                    .addLast("connect-judge", JudgeTypeInboundHandler())
                    .addLast("exception", ExceptionDuplexHandler())
            }
        })
    val port = ServerStart.serverConfigure.port
    println("http server start at " + port)

    return serverBootstrap.bind(port).sync().channel().closeFuture()
}

private fun setResponse(
    @OptIn(ExperimentalTime::class)
    now: Instant,
    withExpiry1Hour: Boolean,
    cacheLifeTimeSeconds: Long? = null
): suspend MockRequestHandleScope.(request: HttpRequestData) -> HttpResponseData =
    {

        @OptIn(ExperimentalTime::class) val expiry =
            if (withExpiry1Hour) HttpHeaders.Expires to listOf(GMTDate(now.toEpochMilliseconds() + 3600_000).toHttpDate()) else null
        val cache = cacheLifeTimeSeconds?.let { HttpHeaders.CacheControl to listOf("max-age=$it") }
        val contentType = HttpHeaders.ContentType to listOf("application/json")

        val headers = listOf(expiry, cache, contentType).filterNotNull()
        respond(
            content = ByteReadChannel(File(TEST_STATUS_LIST_PATH).readBytes()),
            status = HttpStatusCode.OK,
            headers = headers { headers.forEach { appendAll(it.first, it.second) } }
        )
    }

private fun setJsonResponse(
    @OptIn(ExperimentalTime::class)
    now: Instant,
    body: String,
    expiresHeaderValue: String? = null,
    cacheControlHeaderValue: String? = null,
): suspend MockRequestHandleScope.(request: HttpRequestData) -> HttpResponseData =
    {
        val expiry = expiresHeaderValue?.let { HttpHeaders.Expires to listOf(it) }
        val cache = cacheControlHeaderValue?.let { HttpHeaders.CacheControl to listOf(it) }
        val contentType = HttpHeaders.ContentType to listOf("application/json")

        val headers = listOf(expiry, cache, contentType).filterNotNull()
        respond(
            content = ByteReadChannel(body.toByteArray(StandardCharsets.UTF_8)),
            status = HttpStatusCode.OK,
            headers = headers { headers.forEach { appendAll(it.first, it.second) } }
        )
    }
