site_name: Warden Supreme
site_url: https://a-sit-plus.github.io/warden-supreme/

theme:
  name: material
  logo: assets/images/icon.svg
  favicon: assets/images/icon.svg
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.annotate
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: asp-dark
      font:
        text: Roboto


extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/a-sit-plus/warden-supreme
repo_name: a-sit-plus/warden-supreme

copyright: Copyright &copy; 2025-2026 A-SIT Plus GmbH &bull; <a href="https://plus.a-sit.at/imprint.html" target="_blank">Imprint</a>

plugins:
  - social
  - search
  - macros
  - open-in-new-tab

extra:
  links:
    android_key_attestation: https://developer.android.com/privacy-and-security/security-key-attestation
    android_key_id_attestation: https://source.android.com/docs/security/features/keystore/attestation
    android_rkp_source: https://android.googlesource.com/platform/packages/modules/RemoteKeyProvisioning/+/refs/heads/main
    android_rkp_docs: https://source.android.com/docs/core/ota/modular-system/remote-key-provisioning
    android_compat_overview: https://source.android.com/docs/compatibility/overview
    android_14_cdd: https://source.android.com/docs/compatibility/14/android-14-cdd
    android_keystore_overview: https://developer.android.com/privacy-and-security/keystore
    android_keystore_extraction_prevention: https://developer.android.com/privacy-and-security/keystore#ExtractionPrevention
    android_keystore_strongbox_keymint: https://developer.android.com/privacy-and-security/keystore#StrongBoxKeyMint
    android_keyproperties_api: https://developer.android.com/reference/android/security/keystore/KeyProperties
    android_emulator_headless: https://developer.android.com/studio/run/emulator-commandline
    android_implementer_ref_rollback_resistance: https://source.android.com/docs/security/features/keystore/implementer-ref#rollback_resistance
    android_keystore2_binder_fix: https://android.googlesource.com/platform/system/security/+/b0be7edbf9e34bc409c6d869f936c2eb00925b34
    android_security_bulletin: https://source.android.com/docs/security/bulletin
    github_google_android_key_attestation: https://github.com/google/android-key-attestation
    github_android_keyattestation: https://github.com/android/keyattestation

    ios_devicecheck: https://developer.apple.com/documentation/devicecheck
    ios_validating_apps: https://developer.apple.com/documentation/devicecheck/validating-apps-that-connect-to-your-server
    ios_attestation_validation: https://developer.apple.com/documentation/devicecheck/attestation-object-validation-guide
    ios_preparing_app_attest: https://developer.apple.com/documentation/devicecheck/preparing-to-use-the-app-attest-service
    ios_assessing_fraud_risk: https://developer.apple.com/documentation/devicecheck/assessing-fraud-risk
    ios_secure_enclave: https://support.apple.com/guide/security/secure-enclave-sec59b0b31ff/web
    ios_build_numbers: https://tidbits.com/2020/07/08/how-to-decode-apple-version-and-build-numbers/

    signum_home: https://a-sit-plus.github.io/signum/
    signum_supreme: https://a-sit-plus.github.io/signum/supreme/
    signum_attestation_docs: https://a-sit-plus.github.io/signum/supreme/#attestation

    ktor: https://ktor.io/
    spring: https://spring.io/
    kotlin: http://kotlinlang.org
    spring_boot_external_config_json: https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.application-json

    github_veehaitch_devicecheck_appattest: https://github.com/veehaitch/devicecheck-appattest
    github_asitplus_authcheckkit: https://github.com/a-sit-plus/AuthCheckKit
    github_asitplus_warden: https://github.com/a-sit-plus/warden
    github_asitplus_warden_roboto: https://github.com/a-sit-plus/warden-roboto/
    warden_site: https://a-sit-plus.github.io/warden/index.html
    warden_api_docs: https://a-sit-plus.github.io/warden/warden/at.asitplus.attestation/-warden/index.html

    android_platform_security_model_paper: https://arxiv.org/abs/1904.05572
    sybil_attack_paper_pdf: https://www.freehaven.net/anonbib/cache/sybil.pdf
    rfc_7049_cbor: https://datatracker.ietf.org/doc/html/rfc7049
    rfc_8152_cose: https://datatracker.ietf.org/doc/html/rfc8152
    gcp_vm_pricing: https://cloud.google.com/compute/vm-instance-pricing
    android_accessibility_abuse: https://iamjosephmj.medium.com/unveiling-accessibility-attacks-on-android-code-examples-and-countermeasures-de16bd25c76c
    digitales_amt_repackaging_repo: https://github.com/eGovPatchesAT/id-austria
    tryigit_keybox_analysis: https://tryigit.dev/android-keybox-attestation-analysis/#chapter-5
    tryigit_keybox_vip: https://tryigit.dev/keybox/vip/#pricing

  social:
    - icon: fontawesome/solid/earth-americas
      link: https://plus.a-sit.at/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<opensource@a-sit.at>

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      dedent_subsections: true
      base_path:
        - ../supreme/verifier/src/jvmTest/kotlin/examples/
        - ../supreme/client/src/commonTest/kotlin/examples/
        - docs/examples/
        - ../supreme/config-spring/src/test/kotlin
        - ../supreme/config-spring/src/test/java
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - md_in_html
  - attr_list

nav:
    - Docs Hub:
        - Overview: overview.md
        - Why Warden Supreme: why-supreme.md
        - Background:
            - Remote Attestation Primer: bg/primer.md
            - Platform Specifics: bg/platforms.md
            - Threat Models and Risks: bg/threatmodels.md
            - Privacy and Data Protection: bg/privacy.md
        - Technical Deep Dive:
            - Android:
                - Attestation Model: technical/android.md
                - Leaked KeyBoxes: technical/android/leakedkeys.md
            - iOS DeviceCheck &amp; App&nbsp;Attest: technical/ios.md
            - Quirks and Hints: technical/quirks.md
        - Testing: testing.md
        - References: refs.md
    - Integration Guide:
        - Integrating Warden Supreme:
            - End-to-End Integration: integration/supreme.md
            - Externalising Configuration: integration/config.md
            - Error Handling: integration/errorhandling.md
            - Data Model and Schema: integration/datamodel.md
        - Project Structure: integration/structure.md
        - Debugging: integration/debugging.md
        - Usage without Integrated Clients: integration/raw.md
        - Migration from WARDEN: integration/migration.md
        - Changelog: CHANGELOG.md
    - SBOM:
        - Overview: sbom.md
        - Warden makoto: sbom/modules/makoto.md
        - Warden roboto: sbom/modules/roboto.md
        - Supreme Common: sbom/modules/supreme-common.md
        - Supreme Client: sbom/modules/supreme-client.md
        - Supreme Verifier: sbom/modules/supreme-verifier.md
        - Config Hoplite: sbom/modules/config-hoplite.md
        - Config Spring: sbom/modules/config-spring.md
    - Glossary: glossary.md
    - API Docs: dokka/index.html
    - 💎 Services: services.md
