name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./gradlew test assemble
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: All Tests
          path: radix/build/test-results/**/TEST*.xml,sanctor/build/test-results/**/TEST*.xml,servus/build/test-results/**/TEST*.xml
          reporter: java-junit