name: Publish to GitHub
on:
  workflow_dispatch:
    inputs:
      kotlin-version:
        description: 'Override Kotlin version?'
        required: false
        default: ''
        type: string
      kotest-version:
        description: 'Override Kotest version?'
        required: false
        default: ''
        type: string
      ksp-version:
        description: 'Override KSP version? (full version string)?'
        required: false
        default: ''
        type: string
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build-private:
    name: build
    if: ${{ github.event.repository.private }}
    runs-on: [self-hosted, linux]
    container:
      image: ghcr.io/a-sit-plus/docker-android-sdk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env: &build-env
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
      KOTEST_VERSION_ENV: ${{ inputs.kotest-version }}
      KSP_VERSION_ENV: ${{ inputs.ksp-version }}
    steps: &build-steps
      - name: Trust workspace repositories
        if: ${{ github.event.repository.private }}
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/warden-roboto"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/keyattestation"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/android-key-attestation"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/http-proxy"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Publish to GitHub Repo
        run: ./gradlew -PpublishVersionCatalog=false clean publishAllPublicationsToGitHubPackagesRepository
        env:
          SIGN_LOCAL_REPO_ARTEFACTS: 'true'
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.PUBLISH_SIGNING_KEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PUBLISH_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PUBLISH_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.PUBLISH_SONATYPE_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.PUBLISH_SONATYPE_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
  build-public:
    name: build
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    env: *build-env
    steps: *build-steps
