name: Test makoto + roboto
on: [push]
permissions:
  contents: read
  packages: read
  checks: write
jobs:
  test-private:
    name: test
    if: ${{ github.event.repository.private }}
    runs-on: [self-hosted, linux]
    container:
      image: ghcr.io/a-sit-plus/docker-android-sdk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps: &test-steps
      - name: Trust workspace repositories
        if: ${{ github.event.repository.private }}
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/warden-roboto"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/keyattestation"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/android-key-attestation"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/http-proxy"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Tests
        run: ./gradlew :makoto:test :roboto:test
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: All Tests
          path: serverside/**/build/test-results/**/TEST*.xml,utils/**/build/test-results/**/TEST*.xml,supreme/**/build/test-results/**/TEST*.xml
          list-suites: failed
          list-tests: failed
          reporter: java-junit
          use-actions-summary: true
  test-public:
    name: test
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    steps: *test-steps
