name: Test Manually
on:
  workflow_dispatch:
    inputs:
      kotlin-version:
        description: 'Override Kotlin version?'
        required: false
        default: ''
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./gradlew :makoto:test :roboto:test assemble
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: All Tests
          path: serverside/**/build/test-results/**/TEST*.xml,utils/**/build/test-results/**/TEST*.xml,supreme/**/build/test-results/**/TEST*.xml
          list-suites: failed
          list-tests: failed
          reporter: java-junit
          use-actions-summary: true