name: Test Android implementation
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Accept Android SDK licences
        run: yes | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --licenses
      - name: Add ADB to Path
        run: echo "${ANDROID_HOME}/platform-tools" >> "$GITHUB_PATH"
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Connected Check
        run: |
          # start logcat in the background
          adb start-server
          adb devices                                # makes sure the daemon is up
          adb logcat -v time &                       # stream to stdout
          LOGCAT_PID=$!
          ./gradlew :supreme-client:pixel2api33Setup :supreme-verifier:jvmTestClasses startVerifier pixel2api33Check
          kill "$LOGCAT_PID" || true
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Warden Supreme Android Connected Tests
          path: supreme/client/build/outputs/androidTest-results/managedDevice/debug/**/TEST*.xml
          reporter: java-junit
