name: Test Manually
on:
  workflow_dispatch:
    inputs:
      kotlin-version:
        description: 'Override Kotlin version?'
        required: false
        default: ''
        type: string
permissions:
  contents: read
  packages: read
  checks: write
jobs:
  build-private:
    name: build
    if: ${{ github.event.repository.private }}
    runs-on: [self-hosted, linux]
    container:
      image: ghcr.io/a-sit-plus/docker-android-sdk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env: &build-env
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
    steps: &build-steps
      - name: Trust workspace repositories
        if: ${{ github.event.repository.private }}
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/warden-roboto"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/keyattestation"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/android-key-attestation"
          git config --system --add safe.directory "$GITHUB_WORKSPACE/dependencies/http-proxy"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./gradlew test jvmTest assemble
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: All Tests
          path: serverside/**/build/test-results/**/TEST*.xml,utils/**/build/test-results/**/TEST*.xml,supreme/**/build/test-results/**/TEST*.xml
          list-suites: failed
          list-tests: failed
          reporter: java-junit
          use-actions-summary: true
  build-public:
    name: build
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    env: *build-env
    steps: *build-steps
